/-
# The number of subgroups of the symmetric group `S n`
A single self-contained development.  Write `s(n) := Nat.card (Subgroup (Equiv.Perm (Fin n)))`
for the number of subgroups of `S n`.  The contents, in order:
1. `shiftPerm` : elementary abelian `2`-groups inside `S n`, from disjoint transpositions.
2. `exists_generating_finset` / `card_subgroup_le` : every subgroup of a finite group `G` is
   generated by `≤ log₂ |G|` elements, hence `#Subgroup G ≤ |G| ^ log₂ |G|`.
3. `card_submodule_le` : `#{subspaces of F₂^D} ≤ 2 ^ (D + D²/4)` (reduced row echelon form).
4. `graphSubgroup` : `2 ^ (a*b)` distinct subgroups inside an elementary abelian group.
5. Lower bound : `2 ^ (n²/16 - n) ≤ s(n)`, all witnesses elementary abelian of order `2 ^ ⌊n/4⌋`.
6. Main asymptotics for `s(n)`.
7. The sharp count of the elementary abelian `2`-subgroups: their number is
   `2 ^ ((1/16 + o(1)) n²)`, unconditionally and with no appeal to the classification of
   finite simple groups.
8. Pyber's theorem: the CFSG-dependent upper half stated as an explicit hypothesis
   (never an axiom), and the two sharp consequences derived from it.
A summary of the headline statements is at the end of the file.
-/
import Mathlib
/-!
# Shift permutations
For a type `Y` and an additive group `A`, a vector `c : Y → A` acts on `Y × A` by
translating the second coordinate in the fibre over `y` by `c y`.  This produces a
faithful (injective) group homomorphism
`Multiplicative (Y → A) →* Equiv.Perm (Y × A)`,
which for `A = ZMod 2` realises an elementary abelian `2`-group of rank `|Y|`
inside the symmetric group on `2 * |Y|` points, as a group generated by
`|Y|` disjoint transpositions.
-/
namespace SubgroupCount
/-- The permutation of `Y × A` translating the fibre over `y` by `c y`. -/
def shiftPerm {Y : Type*} {A : Type*} [AddGroup A] (c : Y → A) : Equiv.Perm (Y × A) where
  toFun p := (p.1, p.2 + c p.1)
  invFun p := (p.1, p.2 - c p.1)
  left_inv p := by simp
  right_inv p := by simp
@[simp] lemma shiftPerm_apply {Y : Type*} {A : Type*} [AddGroup A] (c : Y → A) (p : Y × A) :
    shiftPerm c p = (p.1, p.2 + c p.1) := rfl
/-- The group homomorphism from the group of vectors `Y → A` to the symmetric group on
`Y × A` given by fibrewise translation. -/
def shiftHom (Y : Type*) (A : Type*) [AddCommGroup A] :
    Multiplicative (Y → A) →* Equiv.Perm (Y × A) where
  toFun c := shiftPerm (Multiplicative.toAdd c)
  map_one' := by ext p <;> simp
  map_mul' c d := by ext p <;> simp [add_comm, add_left_comm]
@[simp] lemma shiftHom_apply {Y : Type*} {A : Type*} [AddCommGroup A]
    (c : Multiplicative (Y → A)) :
    shiftHom Y A c = shiftPerm (Multiplicative.toAdd c) := rfl
theorem shiftHom_injective (Y : Type*) (A : Type*) [AddCommGroup A] :
    Function.Injective (shiftHom Y A) := by
  intro c d h
  ext y
  have := congrArg (fun (p : Equiv.Perm (Y × A)) => (p (y, 0)).2) h
  simpa using this
end SubgroupCount
/-!
# An unconditional upper bound for the number of subgroups of a finite group
Every subgroup of a finite group `G` can be generated by at most `log₂ |G|` elements
(each step of a maximal chain of subgroups at least doubles the order).  Consequently a
finite group has at most `|G| ^ (log₂ |G|)` subgroups.  For `G = S n` this gives the
unconditional bound `2 ^ O(n² log² n)`.
-/
namespace SubgroupCount
open Subgroup
/-- Among the proper subgroups of a subgroup `K` of a finite group there is one of maximal
order.  (Proved with `Nat.findGreatest`, so that no finiteness instance on `Subgroup G`
is needed.) -/
theorem exists_max_card_lt {G : Type*} [Group G] [Finite G] (K : Subgroup G)
    (hne : ∃ M : Subgroup G, M < K) :
    ∃ M : Subgroup G, M < K ∧ ∀ M' : Subgroup G, M' < K → Nat.card M' ≤ Nat.card M := by
  classical
  set p : ℕ → Prop := fun j => ∃ M : Subgroup G, M < K ∧ Nat.card M = j with hp
  have hbound : ∀ {j : ℕ}, p j → j ≤ Nat.card K := by
    rintro j ⟨M, hM, rfl⟩
    exact Nat.le_of_dvd Nat.card_pos (Subgroup.card_dvd_of_le hM.le)
  obtain ⟨M₀, hM₀⟩ := hne
  have hp0 : p (Nat.card M₀) := ⟨M₀, hM₀, rfl⟩
  obtain ⟨M, hMlt, hMcard⟩ : p (Nat.findGreatest p (Nat.card K)) :=
    Nat.findGreatest_spec (hbound hp0) hp0
  refine ⟨M, hMlt, fun M' hM' => ?_⟩
  have hM'p : p (Nat.card M') := ⟨M', hM', rfl⟩
  rw [hMcard]
  exact Nat.le_findGreatest (hbound hM'p) hM'p
/-- Auxiliary induction: every subgroup `K` of a finite group has a generating set `s`
contained in `K` with `2 ^ |s| ≤ |K|`. -/
theorem exists_generating_finset_aux (G : Type*) [Group G] [Finite G] :
    ∀ (m : ℕ) (K : Subgroup G), Nat.card K ≤ m →
      ∃ s : Finset G, ↑s ⊆ (K : Set G) ∧ closure (s : Set G) = K ∧ 2 ^ s.card ≤ Nat.card K := by
  intro m
  induction m with
  | zero =>
      intro K hK
      have := Nat.card_pos (α := K)
      omega
  | succ m ih =>
      intro K hK
      by_cases hbot : K = ⊥
      · refine ⟨∅, by simp [hbot], by simp [hbot], ?_⟩
        simp only [Finset.card_empty, pow_zero]
        exact Nat.card_pos
      · -- choose a proper subgroup of `K` of maximal order
        classical
        have hne : ∃ M : Subgroup G, M < K := ⟨⊥, lt_of_le_of_ne bot_le (Ne.symm hbot)⟩
        obtain ⟨M, hM, hMmax⟩ := exists_max_card_lt K hne
        -- `M` is a maximal proper subgroup of `K`
        have hMK : M ≤ K := hM.le
        have hdvd : Nat.card M ∣ Nat.card K := Subgroup.card_dvd_of_le hMK
        have hMne : Nat.card M ≠ Nat.card K := by
          intro h
          exact hM.ne (Subgroup.eq_of_le_of_card_ge hMK h.ge)
        have hdouble : 2 * Nat.card M ≤ Nat.card K := by
          obtain ⟨k, hk⟩ := hdvd
          have hMpos : 0 < Nat.card M := Nat.card_pos
          have hKpos : 0 < Nat.card K := Nat.card_pos
          have hk2 : 2 ≤ k := by
            rcases Nat.lt_or_ge k 2 with h | h
            · interval_cases k <;> omega
            · exact h
          calc 2 * Nat.card M ≤ k * Nat.card M := Nat.mul_le_mul_right _ hk2
            _ = Nat.card K := by rw [hk]; ring
        have hMcard : Nat.card M ≤ m := by
          have : 0 < Nat.card M := Nat.card_pos
          omega
        obtain ⟨s, hsM, hsclosure, hscard⟩ := ih M hMcard
        -- pick an element of `K` outside `M`
        obtain ⟨x, hxK, hxM⟩ : ∃ x, x ∈ K ∧ x ∉ M := by
          by_contra hcon
          refine hM.ne (le_antisymm hMK fun y hy => ?_)
          by_contra hyM
          exact hcon ⟨y, hy, hyM⟩
        have hxs : x ∉ s := fun hx => hxM (hsM hx)
        refine ⟨insert x s, ?_, ?_, ?_⟩
        · intro y hy
          simp only [Finset.coe_insert, Set.mem_insert_iff] at hy
          rcases hy with rfl | hy
          · exact hxK
          · exact hMK (hsM hy)
        · -- `⟨M, x⟩ = K` by maximality of `|M|`
          have hle : closure ((insert x s : Finset G) : Set G) ≤ K := by
            rw [Subgroup.closure_le]
            intro y hy
            simp only [Finset.coe_insert, Set.mem_insert_iff] at hy
            rcases hy with rfl | hy
            · exact hxK
            · exact hMK (hsM hy)
          by_contra hlt
          have hltK : closure ((insert x s : Finset G) : Set G) < K := lt_of_le_of_ne hle hlt
          have hMlt : M < closure ((insert x s : Finset G) : Set G) := by
            refine lt_of_le_of_ne ?_ ?_
            · rw [← hsclosure]
              exact closure_mono (by simp [Finset.coe_insert, Set.subset_insert])
            · intro h
              exact hxM (h ▸ (subset_closure (by simp) : x ∈ closure ((insert x s : Finset G) : Set G)))
          have hmax2 := hMmax (closure ((insert x s : Finset G) : Set G)) hltK
          have hcardlt : Nat.card M < Nat.card (closure ((insert x s : Finset G) : Set G)) := by
            refine lt_of_le_of_ne (Nat.le_of_dvd Nat.card_pos (Subgroup.card_dvd_of_le hMlt.le)) ?_
            intro h
            exact hMlt.ne (Subgroup.eq_of_le_of_card_ge hMlt.le h.ge)
          omega
        · have : (insert x s).card = s.card + 1 := Finset.card_insert_of_notMem hxs
          rw [this, pow_succ]
          calc 2 ^ s.card * 2 ≤ Nat.card M * 2 := Nat.mul_le_mul_right _ hscard
            _ = 2 * Nat.card M := by ring
            _ ≤ Nat.card K := hdouble
/-- Every subgroup `K` of a finite group is generated by a set `s ⊆ K` with `2 ^ |s| ≤ |K|`,
i.e. by at most `log₂ |K|` elements. -/
theorem exists_generating_finset {G : Type*} [Group G] [Finite G] (K : Subgroup G) :
    ∃ s : Finset G, ↑s ⊆ (K : Set G) ∧ closure (s : Set G) = K ∧ 2 ^ s.card ≤ Nat.card K :=
  exists_generating_finset_aux G (Nat.card K) K le_rfl
/-- A finite group `G` has at most `|G| ^ log₂ |G|` subgroups. -/
theorem card_subgroup_le (G : Type*) [Group G] [Finite G] :
    Nat.card (Subgroup G) ≤ (Nat.card G) ^ (Nat.log 2 (Nat.card G)) := by
  classical
  set N := Nat.card G with hN
  set d := Nat.log 2 N with hd
  have hNpos : 0 < N := Nat.card_pos
  -- a choice of generating tuple for each subgroup
  have hchoice : ∀ K : Subgroup G, ∃ f : Fin d → G, closure (Set.range f) = K := by
    intro K
    obtain ⟨s, hsK, hsclosure, hscard⟩ := exists_generating_finset K
    have hsle : s.card ≤ d := by
      have h1 : 2 ^ s.card ≤ N := le_trans hscard (Nat.card_le_card_of_injective _ Subtype.val_injective)
      exact (Nat.le_log_iff_pow_le (by norm_num) hNpos.ne').mpr h1
    refine ⟨fun i => s.toList.getD i 1, ?_⟩
    apply le_antisymm
    · rw [Subgroup.closure_le]
      rintro y ⟨i, rfl⟩
      show s.toList.getD (i : ℕ) 1 ∈ (K : Set G)
      by_cases hi : (i : ℕ) < s.toList.length
      · have : s.toList.getD (i : ℕ) 1 = s.toList[(i : ℕ)] := List.getD_eq_getElem _ _ hi
        rw [this]
        exact hsK (Finset.mem_toList.mp (List.getElem_mem hi))
      · rw [List.getD_eq_default _ _ (by omega)]
        exact one_mem K
    · rw [← hsclosure]
      apply Subgroup.closure_mono
      intro y hy
      have hy' : y ∈ s.toList := Finset.mem_toList.mpr (by simpa using hy)
      obtain ⟨i, hi, hget⟩ := List.getElem_of_mem hy'
      have hilen : i < d := lt_of_lt_of_le (by simpa [Finset.length_toList] using hi) hsle
      refine ⟨⟨i, hilen⟩, ?_⟩
      show s.toList.getD i 1 = y
      rw [List.getD_eq_getElem _ _ hi]
      exact hget
  choose F hF using hchoice
  have hinj : Function.Injective F := by
    intro K K' h
    rw [← hF K, ← hF K', h]
  calc Nat.card (Subgroup G) ≤ Nat.card (Fin d → G) := Nat.card_le_card_of_injective F hinj
    _ = N ^ d := by simp [Nat.card_fun, hN]
end SubgroupCount
/-!
# Counting the subspaces of `F₂ ^ D`, sharply
The number of subgroups of an elementary abelian `2`-group of order `2 ^ D` is
`2 ^ (D²/4 + O(D))`.  This file proves the *upper* bound
`#{W ≤ F₂^D} ≤ 2 ^ D * 2 ^ ⌊D²/4⌋`,
by the classical "pivot set" (reduced row echelon form) injection: a subspace `W` is
determined by a set `P` of coordinates onto which it projects bijectively, together with the
matrix expressing the remaining coordinates as linear functions of the pivot coordinates.
The matching lower bound `2 ^ (⌊D/2⌋ * ⌈D/2⌉)` is provided by the graph subgroups
constructed in section 4 below.
-/
set_option maxRecDepth 8000
set_option maxHeartbeats 1000000
namespace SubgroupCount
open Finset
variable {D : ℕ}
/-- The data of a row echelon description: a set `P` of pivot coordinates and a matrix
expressing the non-pivot coordinates in terms of the pivot ones. -/
abbrev EchelonData (D : ℕ) :=
  (P : Finset (Fin D)) × ({i : Fin D // i ∈ P} → {j : Fin D // j ∉ P} → ZMod 2)
/-- The subspace described by a piece of echelon data. -/
def echelonSet (d : EchelonData D) : Set (Fin D → ZMod 2) :=
  {x | ∀ j : {j : Fin D // j ∉ d.1}, x j.1 = ∑ i : {i : Fin D // i ∈ d.1}, d.2 i j * x i.1}
/-- If a set of coordinates separates the points of `W` and is minimal with that property,
then `W` projects *bijectively* onto those coordinates.  This is the key step towards the
row echelon normal form. -/
theorem exists_pivot_set (W : Submodule (ZMod 2) (Fin D → ZMod 2)) :
    ∃ P : Finset (Fin D),
      Function.Bijective (fun (w : W) (i : {x : Fin D // x ∈ P}) => (w : Fin D → ZMod 2) i) := by
  classical
  set p : Finset (Fin D) → Prop :=
    fun P => Function.Injective (fun (w : W) (i : {x : Fin D // x ∈ P}) => (w : Fin D → ZMod 2) i)
    with hp
  have huniv : p Finset.univ := by
    intro w w' h
    apply Subtype.ext
    funext i
    exact congrFun h ⟨i, Finset.mem_univ i⟩
  have hne : (Finset.univ.filter (fun P : Finset (Fin D) => p P)).Nonempty :=
    ⟨Finset.univ, by simp [huniv]⟩
  obtain ⟨P, hPmem, hPmin⟩ := Finset.exists_min_image _ Finset.card hne
  simp only [Finset.mem_filter, Finset.mem_univ, true_and] at hPmem
  refine ⟨P, hPmem, ?_⟩
  by_contra hsurj
  set L : W →ₗ[ZMod 2] ({x : Fin D // x ∈ P} → ZMod 2) :=
    { toFun := fun w i => (w : Fin D → ZMod 2) i
      map_add' := by intros; rfl
      map_smul' := by intros; rfl } with hL
  have hbij' : Function.Bijective L → False := fun h => hsurj h.2
  have hlt : LinearMap.range L < ⊤ := by
    refine lt_of_le_of_ne le_top ?_
    intro h
    apply hsurj
    intro y
    have hy : y ∈ LinearMap.range L := by rw [h]; trivial
    obtain ⟨w, hw⟩ := hy
    exact ⟨w, hw⟩
  obtain ⟨φ, hφ0, hφ⟩ := Submodule.exists_dual_map_eq_bot_of_lt_top hlt inferInstance
  set c : {x : Fin D // x ∈ P} → ZMod 2 := fun i => φ (fun j => if i = j then 1 else 0) with hc
  have hcne : ∃ i, c i ≠ 0 := by
    by_contra hcon0
    have hcon : ∀ i, c i = 0 := fun i => not_not.mp fun h => hcon0 ⟨i, h⟩
    apply hφ0
    apply LinearMap.ext
    intro x
    rw [LinearMap.pi_apply_eq_sum_univ φ x]
    simp only [hc] at hcon
    simp [hcon]
  obtain ⟨i₀, hi₀⟩ := hcne
  have key : ∀ w : W, ∑ i, ((w : Fin D → ZMod 2) i.1) * c i = 0 := by
    intro w
    have hmem : L w ∈ LinearMap.range L := ⟨w, rfl⟩
    have hzero : φ (L w) = 0 := by
      have h2 : φ (L w) ∈ Submodule.map φ (LinearMap.range L) := Submodule.mem_map_of_mem hmem
      rw [hφ, Submodule.mem_bot] at h2
      exact h2
    rw [LinearMap.pi_apply_eq_sum_univ φ (L w)] at hzero
    simpa [hc, hL, smul_eq_mul] using hzero
  have hsmall : p (P.erase i₀.1) := by
    intro w w' h
    have hd : ∀ i : {x : Fin D // x ∈ P}, i ≠ i₀ →
        (w : Fin D → ZMod 2) i.1 = (w' : Fin D → ZMod 2) i.1 := by
      intro i hi
      have hmem : i.1 ∈ P.erase i₀.1 := Finset.mem_erase.mpr ⟨fun hh => hi (Subtype.ext hh), i.2⟩
      exact congrFun h ⟨i.1, hmem⟩
    have hi0 : (w : Fin D → ZMod 2) i₀.1 = (w' : Fin D → ZMod 2) i₀.1 := by
      have h1 := key w
      have h2 := key w'
      have hmul : ((w : Fin D → ZMod 2) i₀.1) * c i₀ = ((w' : Fin D → ZMod 2) i₀.1) * c i₀ := by
        have e1 : ∑ i, ((w : Fin D → ZMod 2) i.1) * c i
            = ∑ i, ((w' : Fin D → ZMod 2) i.1) * c i := by rw [h1, h2]
        rw [← Finset.add_sum_erase _ _ (Finset.mem_univ i₀),
          ← Finset.add_sum_erase _ _ (Finset.mem_univ i₀)] at e1
        have e2 : ∑ i ∈ Finset.univ.erase i₀, ((w : Fin D → ZMod 2) i.1) * c i
            = ∑ i ∈ Finset.univ.erase i₀, ((w' : Fin D → ZMod 2) i.1) * c i := by
          refine Finset.sum_congr rfl ?_
          intro i hi
          rw [hd i (Finset.mem_erase.mp hi).1]
        rw [e2] at e1
        exact add_right_cancel e1
      have hcinv : c i₀ = 1 := by
        have hz : ∀ z : ZMod 2, z ≠ 0 → z = 1 := by decide
        exact hz _ hi₀
      rw [hcinv, mul_one, mul_one] at hmul
      exact hmul
    apply hPmem
    funext i
    by_cases hi : i = i₀
    · subst hi; exact hi0
    · exact hd i hi
  have hmin2 := hPmin (P.erase i₀.1)
    (by simp only [Finset.mem_filter, Finset.mem_univ, true_and]; exact hsmall)
  have hlt2 : (P.erase i₀.1).card < P.card := Finset.card_erase_lt_of_mem i₀.2
  omega
/-- **Row echelon normal form.**  Every subspace `W ≤ F₂^D` is the solution set of a system
expressing the non-pivot coordinates as linear combinations of the pivot coordinates. -/
theorem exists_echelon_description (W : Submodule (ZMod 2) (Fin D → ZMod 2)) :
    ∃ d : EchelonData D, (W : Set (Fin D → ZMod 2)) = echelonSet d := by
  classical
  obtain ⟨P, hbij⟩ := exists_pivot_set W
  set L : W →ₗ[ZMod 2] ({x : Fin D // x ∈ P} → ZMod 2) :=
    { toFun := fun w i => (w : Fin D → ZMod 2) i
      map_add' := by intros; rfl
      map_smul' := by intros; rfl } with hL
  have hbij' : Function.Bijective L := hbij
  set e : W ≃ₗ[ZMod 2] ({x : Fin D // x ∈ P} → ZMod 2) := LinearEquiv.ofBijective L hbij' with he
  set g : ({x : Fin D // x ∈ P} → ZMod 2) →ₗ[ZMod 2] W := e.symm.toLinearMap with hg
  refine ⟨⟨P, fun i j => ((g (fun k => if i = k then 1 else 0) : W) : Fin D → ZMod 2) j.1⟩, ?_⟩
  ext x
  show x ∈ W ↔ _
  set y : {x : Fin D // x ∈ P} → ZMod 2 := fun i => x i.1 with hy
  have hgy : ∀ j : Fin D, ((g y : W) : Fin D → ZMod 2) j
      = ∑ i : {x : Fin D // x ∈ P},
          ((g (fun k => if i = k then 1 else 0) : W) : Fin D → ZMod 2) j * y i := by
    intro j
    have h1 := LinearMap.pi_apply_eq_sum_univ g y
    have h2 := congrFun (congrArg Subtype.val h1) j
    rw [h2]
    push_cast
    simp [Finset.sum_apply, mul_comm]
  have hey : ∀ w : W, ∀ i : {x : Fin D // x ∈ P}, (e w) i = (w : Fin D → ZMod 2) i.1 := by
    intro w i; rfl
  have hgy_e : e (g y) = y := by rw [hg]; simp
  constructor
  · intro hx j
    have hw : e ⟨x, hx⟩ = y := by funext i; rw [hey]
    have hge : g (e ⟨x, hx⟩) = (⟨x, hx⟩ : W) := by
      rw [hg]; exact e.symm_apply_apply _
    have heq : (⟨x, hx⟩ : W) = g y := by rw [← hw, hge]
    have hxj : x j.1 = ((g y : W) : Fin D → ZMod 2) j.1 :=
      congrFun (congrArg Subtype.val heq) j.1
    rw [hxj, hgy j.1]
  · intro hrel
    have hxeq : x = ((g y : W) : Fin D → ZMod 2) := by
      funext j
      by_cases hj : j ∈ P
      · have h4 := hey (g y) ⟨j, hj⟩
        rw [hgy_e] at h4
        simpa [hy] using h4
      · rw [hgy j]
        exact hrel ⟨j, hj⟩
    rw [hxeq]
    exact (g y).2
/-- The number of pairs (pivot set, matrix) is at most `2 ^ D * 2 ^ ⌊D²/4⌋`. -/
theorem card_echelon_data_le (D : ℕ) :
    Nat.card (EchelonData D) ≤ 2 ^ D * 2 ^ (D * D / 4) := by
  classical
  have haux : ∀ r : ℕ, r ≤ D → r * (D - r) ≤ D * D / 4 := by
    intro r h
    have key : 4 * (r * (D - r)) ≤ D * D := by
      zify [h]
      nlinarith [sq_nonneg ((D : ℤ) - 2 * r)]
    omega
  rw [EchelonData, Nat.card_sigma]
  have hterm : ∀ P : Finset (Fin D),
      Nat.card ({i : Fin D // i ∈ P} → {j : Fin D // j ∉ P} → ZMod 2) ≤ 2 ^ (D * D / 4) := by
    intro P
    have h1 : Nat.card ({i : Fin D // i ∈ P} → {j : Fin D // j ∉ P} → ZMod 2)
        = 2 ^ (P.card * (D - P.card)) := by
      rw [Nat.card_fun, Nat.card_fun]
      simp only [Nat.card_eq_fintype_card, Fintype.card_subtype_compl, Fintype.card_coe,
        Fintype.card_fin, ZMod.card]
      rw [← pow_mul, Nat.mul_comm]
    rw [h1]
    exact Nat.pow_le_pow_right (by norm_num) (haux _ (by simpa using Finset.card_le_univ P))
  calc ∑ P : Finset (Fin D), Nat.card ({i : Fin D // i ∈ P} → {j : Fin D // j ∉ P} → ZMod 2)
      ≤ ∑ _P : Finset (Fin D), 2 ^ (D * D / 4) := Finset.sum_le_sum (fun P _ => hterm P)
    _ = 2 ^ D * 2 ^ (D * D / 4) := by simp [Finset.sum_const, smul_eq_mul]
/-- **Upper bound for the number of subspaces of `F₂^D`.** -/
theorem card_submodule_le (D : ℕ) :
    Nat.card (Submodule (ZMod 2) (Fin D → ZMod 2)) ≤ 2 ^ (D + D * D / 4) := by
  classical
  choose d hd using exists_echelon_description (D := D)
  have hinj : Function.Injective d := by
    intro W W' h
    have : (W : Set (Fin D → ZMod 2)) = (W' : Set (Fin D → ZMod 2)) := by
      rw [hd W, hd W', h]
    exact SetLike.coe_injective this
  calc Nat.card (Submodule (ZMod 2) (Fin D → ZMod 2))
      ≤ Nat.card (EchelonData D) := Nat.card_le_card_of_injective d hinj
    _ ≤ 2 ^ D * 2 ^ (D * D / 4) := card_echelon_data_le D
    _ = 2 ^ (D + D * D / 4) := (pow_add 2 D (D * D / 4)).symm
/-- **Upper bound for the number of subgroups of an elementary abelian `2`-group.**
A finite group of exponent dividing `2` and order `2 ^ D` has at most `2 ^ (D + ⌊D²/4⌋)`
subgroups. -/
theorem card_subgroup_le_of_exponent_two {G : Type*} [Group G] [Finite G]
    (hG : ∀ g : G, g * g = 1) {D : ℕ} (hcard : Nat.card G = 2 ^ D) :
    Nat.card (Subgroup G) ≤ 2 ^ (D + D * D / 4) := by
  classical
  -- an exponent-two group is abelian
  have hcomm : ∀ a b : G, a * b = b * a := by
    intro a b
    have hinv : ∀ g : G, g⁻¹ = g := fun g => by
      rw [inv_eq_iff_mul_eq_one]; exact hG g
    have := hG (a * b)
    calc a * b = (a * b)⁻¹ := by rw [hinv]
      _ = b⁻¹ * a⁻¹ := mul_inv_rev a b
      _ = b * a := by rw [hinv, hinv]
  let : CommGroup G := { (inferInstance : Group G) with mul_comm := hcomm }
  let : Module (ZMod 2) (Additive G) :=
    AddCommGroup.zmodModule (n := 2) (by
      intro x
      have : (2 : ℕ) • x = x + x := two_nsmul x
      rw [this]
      exact hG (Additive.toMul x))
  have : Finite (Additive G) := inferInstanceAs (Finite G)
  have : Module.Finite (ZMod 2) (Additive G) := Module.Finite.of_finite
  -- the finrank of `Additive G` is `D`
  have : Fintype (Additive G) := Fintype.ofFinite _
  have hfin : Fintype.card (Additive G) = 2 ^ D := by
    rw [← Nat.card_eq_fintype_card, Nat.card_congr (Additive.toMul : Additive G ≃ G)]
    exact hcard
  have hrank : Module.finrank (ZMod 2) (Additive G) = D := by
    have hpow : (2 : ℕ) ^ Module.finrank (ZMod 2) (Additive G) = 2 ^ D := by
      rw [← hfin, Module.card_eq_pow_finrank (K := ZMod 2) (V := Additive G)]
      simp
    exact Nat.pow_right_injective (le_refl 2) hpow
  let B : Module.Basis (Fin D) (ZMod 2) (Additive G) :=
    Module.finBasisOfFinrankEq (ZMod 2) (Additive G) hrank
  let L : Additive G ≃ₗ[ZMod 2] (Fin D → ZMod 2) := B.equivFun
  have hiso : Nat.card (Subgroup G) = Nat.card (Submodule (ZMod 2) (Fin D → ZMod 2)) := by
    have e1 : Subgroup G ≃ AddSubgroup (Additive G) := Subgroup.toAddSubgroup.toEquiv
    have e2 : AddSubgroup (Additive G) ≃ Submodule (ZMod 2) (Additive G) :=
      (AddSubgroup.toZModSubmodule 2).toEquiv
    have e3 : Submodule (ZMod 2) (Additive G) ≃ Submodule (ZMod 2) (Fin D → ZMod 2) :=
      (Submodule.orderIsoMapComap L).toEquiv
    exact Nat.card_congr (e1.trans (e2.trans e3))
  rw [hiso]
  exact card_submodule_le D
end SubgroupCount
/-!
# Many elementary abelian subgroups
Inside the elementary abelian group `V = (Fin a ⊕ Fin b) → ZMod 2` we exhibit `2 ^ (a * b)`
distinct subgroups of order `2 ^ a`, namely the graphs
`{ c : V | ∀ j, c (inr j) = ∑ i, A j i * c (inl i) }`
of the `2 ^ (a * b)` matrices `A : Fin b → Fin a → ZMod 2`.
-/
namespace SubgroupCount
open Multiplicative
/-- The graph of the matrix `A`, as a subgroup of the (multiplicatively written)
elementary abelian group `(Fin a ⊕ Fin b) → ZMod 2`. -/
def graphSubgroup (a b : ℕ) (A : Fin b → Fin a → ZMod 2) :
    Subgroup (Multiplicative ((Fin a ⊕ Fin b) → ZMod 2)) where
  carrier := {c | ∀ j, toAdd c (Sum.inr j) = ∑ i, A j i * toAdd c (Sum.inl i)}
  mul_mem' := by
    intro c d hc hd j
    have hcj : toAdd c (Sum.inr j) = ∑ i, A j i * toAdd c (Sum.inl i) := hc j
    have hdj : toAdd d (Sum.inr j) = ∑ i, A j i * toAdd d (Sum.inl i) := hd j
    simp [hcj, hdj, Finset.sum_add_distrib, mul_add]
  one_mem' := by intro j; simp
  inv_mem' := by
    intro c hc j
    have hcj : toAdd c (Sum.inr j) = ∑ i, A j i * toAdd c (Sum.inl i) := hc j
    simp [hcj]
lemma mem_graphSubgroup {a b : ℕ} {A : Fin b → Fin a → ZMod 2}
    {c : Multiplicative ((Fin a ⊕ Fin b) → ZMod 2)} :
    c ∈ graphSubgroup a b A ↔ ∀ j, toAdd c (Sum.inr j) = ∑ i, A j i * toAdd c (Sum.inl i) :=
  Iff.rfl
/-- Distinct matrices have distinct graphs. -/
theorem graphSubgroup_injective (a b : ℕ) : Function.Injective (graphSubgroup a b) := by
  intro A B h
  by_contra hne
  obtain ⟨j₀, i₀, hji⟩ : ∃ j i, A j i ≠ B j i := by
    by_contra hc
    exact hne (funext fun j => funext fun i => not_not.mp fun h => hc ⟨j, i, h⟩)
  -- the vector supported on `inl i₀` with the `A`-determined values on the right block
  set c : Multiplicative ((Fin a ⊕ Fin b) → ZMod 2) :=
    ofAdd (Sum.elim (fun i => if i = i₀ then 1 else 0) (fun j => A j i₀)) with hc
  have hcA : c ∈ graphSubgroup a b A := by
    intro j
    simp [hc]
  have hcB : c ∈ graphSubgroup a b B := h ▸ hcA
  have := hcB j₀
  simp [hc] at this
  exact hji this
/-- The graph of `A` is isomorphic, as a set, to the space of vectors on the left block. -/
def graphSubgroupEquiv (a b : ℕ) (A : Fin b → Fin a → ZMod 2) :
    (graphSubgroup a b A) ≃ (Fin a → ZMod 2) where
  toFun c i := toAdd c.1 (Sum.inl i)
  invFun v := ⟨ofAdd (Sum.elim v (fun j => ∑ i, A j i * v i)), by intro j; simp⟩
  left_inv := by
    rintro ⟨c, hc⟩
    apply Subtype.ext
    apply funext
    rintro (i | j)
    · rfl
    · exact ((hc j).symm : (∑ i, A j i * toAdd c (Sum.inl i)) = toAdd c (Sum.inr j))
  right_inv := by intro v; funext i; simp
theorem card_graphSubgroup (a b : ℕ) (A : Fin b → Fin a → ZMod 2) :
    Nat.card (graphSubgroup a b A) = 2 ^ a := by
  rw [Nat.card_congr (graphSubgroupEquiv a b A)]
  simp
end SubgroupCount
/-!
# A lower bound for the number of subgroups of the symmetric group
We construct, inside `Equiv.Perm (Fin n)`, at least `2 ^ (a * b)` distinct subgroups, all of
them elementary abelian of order exactly `2 ^ a`, whenever `2 * (a + b) ≤ n`.
Taking `a ≈ b ≈ n / 4` this gives `2 ^ (n ^ 2 / 16 - O(n))` subgroups of `S n`.
-/
namespace SubgroupCount
open Equiv
/-- An embedding of the `2 * (a + b)`-element set `(Fin a ⊕ Fin b) × ZMod 2` into `Fin n`. -/
noncomputable def blockEmbedding (n a b : ℕ) (h : 2 * (a + b) ≤ n) :
    ((Fin a ⊕ Fin b) × ZMod 2) ↪ Fin n :=
  Classical.choice (Function.Embedding.nonempty_of_card_le (by simpa [mul_comm] using h))
/-- The elementary abelian `2`-group of rank `a + b` embedded in `Equiv.Perm (Fin n)` as a
group generated by `a + b` disjoint transpositions. -/
noncomputable def permHom (n a b : ℕ) (h : 2 * (a + b) ≤ n) :
    Multiplicative ((Fin a ⊕ Fin b) → ZMod 2) →* Perm (Fin n) :=
  (Perm.viaEmbeddingHom (blockEmbedding n a b h)).comp (shiftHom (Fin a ⊕ Fin b) (ZMod 2))
theorem permHom_injective (n a b : ℕ) (h : 2 * (a + b) ≤ n) :
    Function.Injective (permHom n a b h) :=
  (Perm.viaEmbeddingHom_injective _).comp (shiftHom_injective _ _)
/-- The family of subgroups of `Equiv.Perm (Fin n)` indexed by matrices `A : Fin b → Fin a → ZMod 2`,
each of order `2 ^ a`. -/
noncomputable def permGraphSubgroup (n a b : ℕ) (h : 2 * (a + b) ≤ n)
    (A : Fin b → Fin a → ZMod 2) : Subgroup (Perm (Fin n)) :=
  Subgroup.map (permHom n a b h) (graphSubgroup a b A)
theorem card_permGraphSubgroup (n a b : ℕ) (h : 2 * (a + b) ≤ n) (A : Fin b → Fin a → ZMod 2) :
    Nat.card (permGraphSubgroup n a b h A) = 2 ^ a := by
  have := Nat.card_congr
    (Subgroup.equivMapOfInjective (graphSubgroup a b A) (permHom n a b h)
      (permHom_injective n a b h)).toEquiv
  rw [permGraphSubgroup, ← this, card_graphSubgroup]
theorem permGraphSubgroup_injective (n a b : ℕ) (h : 2 * (a + b) ≤ n) :
    Function.Injective (permGraphSubgroup n a b h) :=
  (Subgroup.map_injective (permHom_injective n a b h)).comp (graphSubgroup_injective a b)
/-- Every subgroup produced by the construction is elementary abelian of exponent `2`. -/
theorem sq_eq_one_of_mem_permGraphSubgroup (n a b : ℕ) (h : 2 * (a + b) ≤ n)
    (A : Fin b → Fin a → ZMod 2) {g : Perm (Fin n)} (hg : g ∈ permGraphSubgroup n a b h A) :
    g * g = 1 := by
  obtain ⟨c, -, rfl⟩ := hg
  rw [← map_mul]
  have hcc : c * c = 1 := by
    have : Multiplicative.toAdd (c * c) = Multiplicative.toAdd (1 : Multiplicative
        ((Fin a ⊕ Fin b) → ZMod 2)) := by
      funext y
      simpa using CharTwo.add_self_eq_zero (Multiplicative.toAdd c y)
    exact Multiplicative.toAdd.injective this
  rw [hcc, map_one]
/-- Every subgroup produced by the construction is abelian. -/
theorem commute_of_mem_permGraphSubgroup (n a b : ℕ) (h : 2 * (a + b) ≤ n)
    (A : Fin b → Fin a → ZMod 2) {g₁ g₂ : Perm (Fin n)}
    (hg₁ : g₁ ∈ permGraphSubgroup n a b h A) (hg₂ : g₂ ∈ permGraphSubgroup n a b h A) :
    g₁ * g₂ = g₂ * g₁ := by
  obtain ⟨c, -, rfl⟩ := hg₁
  obtain ⟨d, -, rfl⟩ := hg₂
  rw [← map_mul, ← map_mul, mul_comm]
/-- **Main counting construction.** If `2 * (a + b) ≤ n`, then the symmetric group on `n`
letters has at least `2 ^ (a * b)` subgroups of order exactly `2 ^ a`. -/
theorem pow_le_card_subgroups_of_order (n a b : ℕ) (h : 2 * (a + b) ≤ n) :
    2 ^ (a * b) ≤ Nat.card {H : Subgroup (Perm (Fin n)) // Nat.card H = 2 ^ a} := by
  have hcard : Nat.card (Fin b → Fin a → ZMod 2) = 2 ^ (a * b) := by
    simp [pow_mul]
  rw [← hcard]
  refine Nat.card_le_card_of_injective
    (fun A => ⟨permGraphSubgroup n a b h A, card_permGraphSubgroup n a b h A⟩) ?_
  intro A B hAB
  exact permGraphSubgroup_injective n a b h (Subtype.ext_iff.mp hAB)
end SubgroupCount
/-!
# The number of subgroups of the symmetric group
Let `s(n) := Nat.card (Subgroup (Equiv.Perm (Fin n)))` be the number of subgroups of the
symmetric group `S n`.  We prove unconditionally:
* `two_pow_le_card_subgroups_symm` : `2 ^ (n²/16 - n) ≤ s(n)`, obtained from an explicit
  family of elementary abelian `2`-subgroups;
* `card_subgroups_symm_le` : `s(n) ≤ 2 ^ (n * ⌈log₂ n⌉)²`, obtained from the fact that every
  subgroup of a finite group `G` is generated by at most `log₂ |G|` elements;
* `two_pow_le_card_subgroups_symm_of_order` : the same lower bound already holds for the number
  of subgroups of one single order, namely elementary abelian `2`-groups of order `2 ^ ⌊n/4⌋`;
* `tendsto_logb_logb_card_subgroups_symm` : `log₂ s(n) = n ^ (2 + o(1))`.
-/
namespace SubgroupCount
open Equiv Filter
/-- The number of subgroups of the symmetric group on `n` letters. -/
noncomputable def numSubgroupsSymm (n : ℕ) : ℕ := Nat.card (Subgroup (Perm (Fin n)))
/-! ## The lower bound -/
/-- The elementary abelian construction, with the concrete choice `a = ⌊n/4⌋`, `b = ⌊n/2⌋ - ⌊n/4⌋`:
`S n` has at least `2 ^ (⌊n/4⌋ * (⌊n/2⌋ - ⌊n/4⌋))` subgroups of order exactly `2 ^ ⌊n/4⌋`. -/
theorem pow_le_card_subgroups_symm_of_order (n : ℕ) :
    2 ^ ((n / 4) * (n / 2 - n / 4)) ≤
      Nat.card {H : Subgroup (Perm (Fin n)) // Nat.card H = 2 ^ (n / 4)} :=
  pow_le_card_subgroups_of_order n (n / 4) (n / 2 - n / 4) (by omega)
theorem pow_le_numSubgroupsSymm (n : ℕ) :
    2 ^ ((n / 4) * (n / 2 - n / 4)) ≤ numSubgroupsSymm n := by
  refine le_trans (pow_le_card_subgroups_symm_of_order n) ?_
  exact Nat.card_le_card_of_injective (fun H => H.1) (fun _ _ h => Subtype.ext h)
/-- The elementary bound `n²/16 - n ≤ ⌊n/4⌋ * (⌊n/2⌋ - ⌊n/4⌋)`. -/
theorem sq_div_sixteen_le (n : ℕ) :
    (n : ℝ) ^ 2 / 16 - n ≤ ((n / 4 : ℕ) : ℝ) * ((n / 2 - n / 4 : ℕ) : ℝ) := by
  set a : ℕ := n / 4 with ha
  set b : ℕ := n / 2 - n / 4 with hb
  have h1 : n ≤ 2 * (a + b) + 1 := by omega
  have h2 : 2 * (a + b) ≤ n := by omega
  have h3 : b ≤ a + 1 := by omega
  have h4 : a ≤ b := by omega
  have h1' : (n : ℝ) ≤ 2 * ((a : ℝ) + b) + 1 := by exact_mod_cast h1
  have h2' : 2 * ((a : ℝ) + b) ≤ n := by exact_mod_cast h2
  have h3' : (b : ℝ) ≤ (a : ℝ) + 1 := by exact_mod_cast h3
  have h4' : (a : ℝ) ≤ b := by exact_mod_cast h4
  have ha0 : (0 : ℝ) ≤ a := Nat.cast_nonneg a
  rcases Nat.eq_zero_or_pos a with h0 | hpos
  · -- then `n ≤ 3` and the left-hand side is negative
    have hn3 : n ≤ 3 := by omega
    have : (n : ℝ) ≤ 3 := by exact_mod_cast hn3
    nlinarith [Nat.cast_nonneg (α := ℝ) n, Nat.cast_nonneg (α := ℝ) b]
  · have ha1 : (1 : ℝ) ≤ a := by exact_mod_cast hpos
    nlinarith [Nat.cast_nonneg (α := ℝ) n]
/-- The real-exponent form of the combinatorial bound. -/
theorem two_pow_le_pow (n N : ℕ) (h : 2 ^ ((n / 4) * (n / 2 - n / 4)) ≤ N) :
    (2 : ℝ) ^ ((n : ℝ) ^ 2 / 16 - n) ≤ N := by
  have hcast : ((2 : ℝ) ^ ((((n / 4) * (n / 2 - n / 4) : ℕ)) : ℝ)) ≤ (N : ℝ) := by
    rw [Real.rpow_natCast]
    exact_mod_cast h
  refine le_trans ?_ hcast
  rw [Real.rpow_le_rpow_left_iff (by norm_num), Nat.cast_mul]
  exact sq_div_sixteen_le n
/-- **Unconditional lower bound.** The symmetric group on `n` letters has at least
`2 ^ (n²/16 - n)` subgroups. -/
theorem two_pow_le_card_subgroups_symm (n : ℕ) :
    (2 : ℝ) ^ ((n : ℝ) ^ 2 / 16 - n) ≤ numSubgroupsSymm n :=
  two_pow_le_pow n _ (pow_le_numSubgroupsSymm n)
/-- **Statistical form.**  The lower bound `2 ^ (n²/16 - n)` is already attained by subgroups
of a single order: `S n` has at least `2 ^ (n²/16 - n)` subgroups of order exactly
`2 ^ ⌊n/4⌋`, all of them elementary abelian `2`-groups. -/
theorem two_pow_le_card_subgroups_symm_of_order (n : ℕ) :
    (2 : ℝ) ^ ((n : ℝ) ^ 2 / 16 - n) ≤
      Nat.card {H : Subgroup (Perm (Fin n)) // Nat.card H = 2 ^ (n / 4)} :=
  two_pow_le_pow n _ (pow_le_card_subgroups_symm_of_order n)
/-! ## The upper bound -/
/-- **Unconditional upper bound.** `S n` has at most `2 ^ (n * ⌈log₂ n⌉)²` subgroups. -/
theorem card_subgroups_symm_le (n : ℕ) :
    numSubgroupsSymm n ≤ 2 ^ ((n * Nat.clog 2 n) * (n * Nat.clog 2 n)) := by
  set c := n * Nat.clog 2 n with hc
  have hfac : Nat.factorial n ≤ 2 ^ c := by
    calc Nat.factorial n ≤ n ^ n := Nat.factorial_le_pow n
      _ ≤ (2 ^ Nat.clog 2 n) ^ n := Nat.pow_le_pow_left (Nat.le_pow_clog (by norm_num) n) n
      _ = 2 ^ c := by rw [← pow_mul, hc, mul_comm]
  have hN : Nat.card (Perm (Fin n)) = Nat.factorial n := by simp [Nat.card_eq_fintype_card,
    Fintype.card_perm]
  have h := card_subgroup_le (Perm (Fin n))
  rw [hN] at h
  have hd : Nat.log 2 (Nat.factorial n) ≤ c := by
    calc Nat.log 2 (Nat.factorial n) ≤ Nat.log 2 (2 ^ c) := Nat.log_mono_right hfac
      _ = c := Nat.log_pow (by norm_num) c
  calc numSubgroupsSymm n ≤ Nat.factorial n ^ Nat.log 2 (Nat.factorial n) := h
    _ ≤ (2 ^ c) ^ c :=
        le_trans (Nat.pow_le_pow_left hfac _) (Nat.pow_le_pow_right (by positivity) hd)
    _ = 2 ^ (c * c) := by rw [← pow_mul]
/-! ## The resulting asymptotics -/
private lemma logb2_mono {x y : ℝ} (hx : 0 < x) (h : x ≤ y) : Real.logb 2 x ≤ Real.logb 2 y := by
  unfold Real.logb
  gcongr
private lemma clog_le_logb_add_one (n : ℕ) (hn : 2 ≤ n) :
    (Nat.clog 2 n : ℝ) ≤ Real.logb 2 n + 1 := by
  have h1 : 1 < n := hn
  have h2 : 2 ^ (Nat.clog 2 n - 1) < n := Nat.pow_pred_clog_lt_self (by norm_num) h1
  have hc1 : 1 ≤ Nat.clog 2 n := Nat.clog_pos (by norm_num) h1
  have h3 : ((2 : ℝ) ^ ((Nat.clog 2 n - 1 : ℕ) : ℝ)) ≤ (n : ℝ) := by
    rw [Real.rpow_natCast]
    exact_mod_cast h2.le
  have h4 : ((Nat.clog 2 n - 1 : ℕ) : ℝ) ≤ Real.logb 2 n :=
    (Real.le_logb_iff_rpow_le (by norm_num) (by positivity : (0 : ℝ) < n)).mpr h3
  rw [Nat.cast_sub hc1] at h4
  push_cast at h4
  linarith
theorem numSubgroupsSymm_pos (n : ℕ) : 0 < numSubgroupsSymm n := Nat.card_pos
/-- One-over-`log` bound: for `n ≥ 2` we have `1 ≤ log₂ n`. -/
private lemma one_le_logb (n : ℕ) (hn : 2 ≤ n) : (1 : ℝ) ≤ Real.logb 2 n := by
  have h2n : (2 : ℝ) ≤ n := by exact_mod_cast hn
  calc (1 : ℝ) = Real.logb 2 2 := (Real.logb_self_eq_one (by norm_num : (1 : ℝ) < 2)).symm
    _ ≤ Real.logb 2 n := logb2_mono (by norm_num) h2n
/-- Lower bound in logarithmic form: `log₂ s(n) ≥ n² / 32` for `n ≥ 32`. -/
theorem sq_div_le_logb_numSubgroupsSymm (n : ℕ) (hn : 32 ≤ n) :
    (n : ℝ) ^ 2 / 32 ≤ Real.logb 2 (numSubgroupsSymm n) := by
  have hpos : (0 : ℝ) < numSubgroupsSymm n := by exact_mod_cast numSubgroupsSymm_pos n
  have h := two_pow_le_card_subgroups_symm n
  have h' : (n : ℝ) ^ 2 / 16 - n ≤ Real.logb 2 (numSubgroupsSymm n) :=
    (Real.le_logb_iff_rpow_le (by norm_num) hpos).mpr h
  have hn' : (32 : ℝ) ≤ n := by exact_mod_cast hn
  nlinarith
/-- Upper bound in logarithmic form: `log₂ s(n) ≤ (2 n log₂ n)²` for `n ≥ 2`. -/
theorem logb_numSubgroupsSymm_le (n : ℕ) (hn : 2 ≤ n) :
    Real.logb 2 (numSubgroupsSymm n) ≤ (2 * n * Real.logb 2 n) ^ 2 := by
  set c : ℕ := n * Nat.clog 2 n with hc
  have hpos : (0 : ℝ) < numSubgroupsSymm n := by exact_mod_cast numSubgroupsSymm_pos n
  have hcard : (numSubgroupsSymm n : ℝ) ≤ ((2 : ℝ) ^ (c * c)) := by
    exact_mod_cast card_subgroups_symm_le n
  have h1 : Real.logb 2 (numSubgroupsSymm n) ≤ ((c : ℝ) * c) := by
    refine le_trans (logb2_mono hpos hcard) ?_
    rw [Real.logb_pow]
    simp [Real.logb_self_eq_one]
  have hlogn : (1 : ℝ) ≤ Real.logb 2 n := one_le_logb n hn
  have hn0 : (0 : ℝ) ≤ n := Nat.cast_nonneg n
  have hcle : (c : ℝ) ≤ 2 * n * Real.logb 2 n := by
    have hclog := clog_le_logb_add_one n hn
    have hcast : (c : ℝ) = (n : ℝ) * (Nat.clog 2 n : ℝ) := by rw [hc]; push_cast; ring
    rw [hcast]
    nlinarith
  have hc0 : (0 : ℝ) ≤ (c : ℝ) := Nat.cast_nonneg c
  nlinarith
/-- A squeeze lemma: any counting function `f` with `n²/32 ≤ log₂ (f n) ≤ (2 n log₂ n)²`
satisfies `log₂ (f n) = n ^ (2 + o(1))`. -/
theorem tendsto_logb_logb_of_bounds (f : ℕ → ℕ)
    (hlow : ∀ n : ℕ, 32 ≤ n → (n : ℝ) ^ 2 / 32 ≤ Real.logb 2 (f n))
    (hup : ∀ n : ℕ, 32 ≤ n → Real.logb 2 (f n) ≤ (2 * n * Real.logb 2 n) ^ 2) :
    Tendsto (fun n : ℕ => Real.logb 2 (Real.logb 2 (f n)) / Real.logb 2 n) atTop (nhds 2) := by
  have hlogb : Tendsto (fun n : ℕ => Real.logb 2 (n : ℝ)) atTop atTop :=
    (Real.tendsto_logb_atTop (by norm_num)).comp tendsto_natCast_atTop_atTop
  have hdiv : Tendsto (fun u : ℝ => Real.logb 2 u / u) atTop (nhds 0) := by
    have h : Tendsto (fun u : ℝ => Real.log u / u) atTop (nhds 0) :=
      Real.isLittleO_log_id_atTop.tendsto_div_nhds_zero
    have h2 := h.const_mul (1 / Real.log 2)
    simp only [mul_zero] at h2
    refine h2.congr ?_
    intro u
    simp [Real.logb]
    ring
  have hloglog : Tendsto
      (fun n : ℕ => Real.logb 2 (Real.logb 2 (n : ℝ)) / Real.logb 2 (n : ℝ)) atTop (nhds 0) :=
    hdiv.comp hlogb
  have hinv : Tendsto (fun n : ℕ => 1 / Real.logb 2 (n : ℝ)) atTop (nhds 0) := by
    simpa [one_div, Function.comp_def] using (tendsto_inv_atTop_zero.comp hlogb)
  have hlowlim : Tendsto (fun n : ℕ => 2 - 5 * (1 / Real.logb 2 (n : ℝ))) atTop (nhds 2) := by
    have h := (hinv.const_mul (5 : ℝ)).const_sub (2 : ℝ)
    simpa using h
  have hhighlim : Tendsto (fun n : ℕ => 2 + 2 * (1 / Real.logb 2 (n : ℝ)) +
      2 * (Real.logb 2 (Real.logb 2 (n : ℝ)) / Real.logb 2 (n : ℝ))) atTop (nhds 2) := by
    have h1 := (hinv.const_mul (2 : ℝ)).const_add (2 : ℝ)
    have h2 := hloglog.const_mul (2 : ℝ)
    have h3 := h1.add h2
    simpa using h3
  refine tendsto_of_tendsto_of_tendsto_of_le_of_le' hlowlim hhighlim ?_ ?_
  · filter_upwards [eventually_ge_atTop 32] with n hn
    have hn2 : 2 ≤ n := by omega
    have hd : (1 : ℝ) ≤ Real.logb 2 (n : ℝ) := one_le_logb n hn2
    have hdpos : (0 : ℝ) < Real.logb 2 (n : ℝ) := lt_of_lt_of_le one_pos hd
    have h32 : (32 : ℝ) ≤ n := by exact_mod_cast hn
    have hL : (n : ℝ) ^ 2 / 32 ≤ Real.logb 2 (f n) := hlow n hn
    have hLpos : (0 : ℝ) < (n : ℝ) ^ 2 / 32 := by positivity
    have hstep : Real.logb 2 ((n : ℝ) ^ 2 / 32) ≤
        Real.logb 2 (Real.logb 2 (f n)) := logb2_mono hLpos hL
    have hval : Real.logb 2 ((n : ℝ) ^ 2 / 32) = 2 * Real.logb 2 (n : ℝ) - 5 := by
      have h32' : Real.logb 2 (32 : ℝ) = 5 := by
        rw [show (32 : ℝ) = 2 ^ (5 : ℕ) by norm_num, Real.logb_pow]
        simp [Real.logb_self_eq_one]
      rw [Real.logb_div (by positivity) (by norm_num), Real.logb_pow, h32']
      push_cast
      ring
    rw [hval] at hstep
    have hrw : 2 - 5 * (1 / Real.logb 2 (n : ℝ)) =
        (2 * Real.logb 2 (n : ℝ) - 5) / Real.logb 2 (n : ℝ) := by
      field_simp
    rw [hrw]
    gcongr
  · filter_upwards [eventually_ge_atTop 32] with n hn
    have hn2 : 2 ≤ n := by omega
    have hd : (1 : ℝ) ≤ Real.logb 2 (n : ℝ) := one_le_logb n hn2
    have hdpos : (0 : ℝ) < Real.logb 2 (n : ℝ) := lt_of_lt_of_le one_pos hd
    have h32 : (32 : ℝ) ≤ n := by exact_mod_cast hn
    have hL : Real.logb 2 (f n) ≤ (2 * n * Real.logb 2 (n : ℝ)) ^ 2 := hup n hn
    have hLpos : (0 : ℝ) < Real.logb 2 (f n) := by
      have hl := hlow n hn
      nlinarith
    have hstep : Real.logb 2 (Real.logb 2 (f n)) ≤
        Real.logb 2 ((2 * (n : ℝ) * Real.logb 2 (n : ℝ)) ^ 2) := logb2_mono hLpos hL
    have hval : Real.logb 2 ((2 * (n : ℝ) * Real.logb 2 (n : ℝ)) ^ 2) =
        2 + 2 * Real.logb 2 (n : ℝ) + 2 * Real.logb 2 (Real.logb 2 (n : ℝ)) := by
      have hn0 : (0 : ℝ) < (n : ℝ) := by linarith
      rw [Real.logb_pow, Real.logb_mul (by positivity) (ne_of_gt hdpos),
        Real.logb_mul (by norm_num) (ne_of_gt hn0)]
      simp [Real.logb_self_eq_one]
      ring
    rw [hval] at hstep
    have hrw : 2 + 2 * (1 / Real.logb 2 (n : ℝ)) +
        2 * (Real.logb 2 (Real.logb 2 (n : ℝ)) / Real.logb 2 (n : ℝ)) =
        (2 + 2 * Real.logb 2 (n : ℝ) + 2 * Real.logb 2 (Real.logb 2 (n : ℝ))) /
          Real.logb 2 (n : ℝ) := by
      field_simp
      ring
    rw [hrw]
    gcongr
/-- **Asymptotic form.**  `log₂ (number of subgroups of `S n`) = n ^ (2 + o(1))`:
the double logarithm of the number of subgroups, divided by `log₂ n`, tends to `2`. -/
theorem tendsto_logb_logb_card_subgroups_symm :
    Tendsto (fun n : ℕ => Real.logb 2 (Real.logb 2 (numSubgroupsSymm n)) / Real.logb 2 n)
      atTop (nhds 2) :=
  tendsto_logb_logb_of_bounds _ (fun n hn => sq_div_le_logb_numSubgroupsSymm n hn)
    (fun n hn => logb_numSubgroupsSymm_le n (by omega))
/-! ## The statistical statement about the orders -/
/-- The number of subgroups of `S n` of order exactly `2 ^ ⌊n/4⌋`. -/
noncomputable def numSubgroupsSymmOfOrder (n : ℕ) : ℕ :=
  Nat.card {H : Subgroup (Perm (Fin n)) // Nat.card H = 2 ^ (n / 4)}
theorem numSubgroupsSymmOfOrder_le (n : ℕ) : numSubgroupsSymmOfOrder n ≤ numSubgroupsSymm n :=
  Nat.card_le_card_of_injective (fun H => H.1) (fun _ _ h => Subtype.ext h)
theorem numSubgroupsSymmOfOrder_pos (n : ℕ) : 0 < numSubgroupsSymmOfOrder n :=
  lt_of_lt_of_le (Nat.two_pow_pos _) (pow_le_card_subgroups_symm_of_order n)
theorem sq_div_le_logb_numSubgroupsSymmOfOrder (n : ℕ) (hn : 32 ≤ n) :
    (n : ℝ) ^ 2 / 32 ≤ Real.logb 2 (numSubgroupsSymmOfOrder n) := by
  have hpos : (0 : ℝ) < numSubgroupsSymmOfOrder n := by
    exact_mod_cast numSubgroupsSymmOfOrder_pos n
  have h : (2 : ℝ) ^ ((n : ℝ) ^ 2 / 16 - n) ≤ numSubgroupsSymmOfOrder n :=
    two_pow_le_card_subgroups_symm_of_order n
  have h' : (n : ℝ) ^ 2 / 16 - n ≤ Real.logb 2 (numSubgroupsSymmOfOrder n) :=
    (Real.le_logb_iff_rpow_le (by norm_num) hpos).mpr h
  have hn' : (32 : ℝ) ≤ n := by exact_mod_cast hn
  nlinarith
/-- **Statistical theorem on the orders.**  Not merely the total number of subgroups, but
already the number of subgroups of the single order `2 ^ ⌊n/4⌋` (all of them elementary
abelian `2`-groups) is `2 ^ (n ^ (2 + o(1)))`.  So on the logarithmic scale the whole count
is carried by `2`-subgroups of that one order. -/
theorem tendsto_logb_logb_card_subgroups_symm_of_order :
    Tendsto (fun n : ℕ => Real.logb 2 (Real.logb 2 (numSubgroupsSymmOfOrder n)) / Real.logb 2 n)
      atTop (nhds 2) := by
  refine tendsto_logb_logb_of_bounds _ (fun n hn => sq_div_le_logb_numSubgroupsSymmOfOrder n hn)
    (fun n hn => ?_)
  have hpos : (0 : ℝ) < numSubgroupsSymmOfOrder n := by
    exact_mod_cast numSubgroupsSymmOfOrder_pos n
  refine le_trans (logb2_mono hpos ?_) (logb_numSubgroupsSymm_le n (by omega))
  exact_mod_cast numSubgroupsSymmOfOrder_le n
end SubgroupCount
/-!
# Elementary abelian `2`-subgroups of the symmetric group: the sharp count
This file proves, unconditionally and without any appeal to the classification of finite
simple groups, that the number of elementary abelian `2`-subgroups of `S n` is
`2 ^ (n²/16 + O(n log n))`.  Together with the lower-bound construction of section 5 (which
produces `2 ^ (n²/16 - n)` such subgroups) this determines the constant `1/16` exactly for
this class of subgroups.
The argument.  Let `A ≤ S n` be a subgroup of exponent `2` (equivalently: elementary
abelian).  Its orbits have `2`-power size, `A` acts regularly on each of them, and therefore
`A` is contained in the group of all permutations which preserve each `A`-orbit and act on it
by a translation of the corresponding `F₂`-vector space.  Such an "ambient" group is encoded
by two cheap pieces of data: a function `c : Fin n → Fin n` naming, for each point, its orbit,
and a function `o : Fin n → F₂^m` (with `m = ⌊log₂ n⌋ + 1`) giving the coordinates of the point
inside its orbit.  There are at most `n ^ n * (2n) ^ n = 2 ^ O(n log n)` such pairs, and each
ambient group `E` is again elementary abelian, so `|E| ≤ 2 ^ ⌊n/2⌋` and, by
`SubgroupCount.card_subgroup_le_of_exponent_two`, `E` has at most `2 ^ (⌊n/2⌋ + ⌊n/2⌋²/4)`
subgroups.  Multiplying the two counts gives the bound.
-/
set_option maxRecDepth 8000
set_option maxHeartbeats 1000000
namespace SubgroupCount
open Equiv
/-- The coordinate space used to label the points inside an orbit: `F₂ ^ (⌊log₂ n⌋ + 1)`,
which is large enough since every orbit has size at most `n`. -/
abbrev Coord (n : ℕ) := Fin (Nat.log 2 n + 1) → ZMod 2
/-- The "block translation group" attached to a labelling `c` of the points by blocks and a
coordinatisation `o` of the points inside their blocks: all permutations preserving every
block and acting on each block by a translation of the coordinates. -/
def blockTransGroup (n : ℕ) (c : Fin n → Fin n) (o : Fin n → Coord n) :
    Subgroup (Perm (Fin n)) where
  carrier := {g | (∀ x, c (g x) = c x) ∧
    ∀ x y, c x = c y → o (g x) - o x = o (g y) - o y}
  mul_mem' := by
    rintro g h ⟨hg1, hg2⟩ ⟨hh1, hh2⟩
    refine ⟨fun x => by simp only [Perm.mul_apply, hg1, hh1], ?_⟩
    intro x y hxy
    have hcx : c (h x) = c (h y) := by rw [hh1, hh1, hxy]
    have h1 := hg2 (h x) (h y) hcx
    have h2 := hh2 x y hxy
    simp only [Perm.mul_apply]
    have h3 : o (g (h x)) - o x = (o (g (h x)) - o (h x)) + (o (h x) - o x) := by ring
    rw [h3, h1, h2]
    ring
  one_mem' := by
    refine ⟨fun x => by simp, ?_⟩
    intro x y _
    simp
  inv_mem' := by
    rintro g ⟨hg1, hg2⟩
    refine ⟨fun x => ?_, ?_⟩
    · have := hg1 (g⁻¹ x)
      simpa using this.symm
    · intro x y hxy
      have hgx : g (g⁻¹ x) = x := by simp
      have hgy : g (g⁻¹ y) = y := by simp
      have hcx : c (g⁻¹ x) = c (g⁻¹ y) := by
        have h1 := hg1 (g⁻¹ x)
        have h2 := hg1 (g⁻¹ y)
        rw [hgx] at h1
        rw [hgy] at h2
        rw [← h1, ← h2, hxy]
      have h5 := hg2 (g⁻¹ x) (g⁻¹ y) hcx
      rw [hgx, hgy] at h5
      have h3 : o (g⁻¹ x) - o x = -(o x - o (g⁻¹ x)) := by ring
      have h4 : o (g⁻¹ y) - o y = -(o y - o (g⁻¹ y)) := by ring
      rw [h3, h4, h5]
lemma mem_blockTransGroup {n : ℕ} {c : Fin n → Fin n} {o : Fin n → Coord n}
    {g : Perm (Fin n)} :
    g ∈ blockTransGroup n c o ↔
      (∀ x, c (g x) = c x) ∧ ∀ x y, c x = c y → o (g x) - o x = o (g y) - o y := Iff.rfl
/-- If the coordinates separate the points of each block, the block translation group has
exponent `2`. -/
theorem blockTransGroup_exponent_two (n : ℕ) (c : Fin n → Fin n) (o : Fin n → Coord n)
    (hinj : ∀ x y : Fin n, c x = c y → o x = o y → x = y) :
    ∀ g ∈ blockTransGroup n c o, g * g = 1 := by
  rintro g ⟨hg1, hg2⟩
  have hself : ∀ v : Coord n, v + v = 0 := by
    intro v; funext i; exact CharTwo.add_self_eq_zero _
  refine Equiv.ext fun x => ?_
  simp only [Perm.mul_apply, Perm.one_apply]
  refine hinj _ _ (by rw [hg1, hg1]) ?_
  have h1 := hg2 (g x) x (hg1 x)
  have h2 : o (g (g x)) = (o (g x) - o x) + o (g x) := sub_eq_iff_eq_add.mp h1
  rw [h2]
  have e1 : (o (g x) - o x) + o (g x) = (o (g x) + o (g x)) - o x := by ring
  rw [e1, hself, zero_sub, neg_eq_iff_add_eq_zero, hself]
/-- A finite group of exponent `2` has `2`-power order. -/
theorem exists_card_eq_two_pow_of_exponent_two {G : Type*} [Group G] [Finite G]
    (hG : ∀ g : G, g * g = 1) : ∃ D : ℕ, Nat.card G = 2 ^ D := by
  classical
  have hcomm : ∀ a b : G, a * b = b * a := by
    intro a b
    have hinv : ∀ g : G, g⁻¹ = g := fun g => by rw [inv_eq_iff_mul_eq_one]; exact hG g
    calc a * b = (a * b)⁻¹ := by rw [hinv]
      _ = b⁻¹ * a⁻¹ := mul_inv_rev a b
      _ = b * a := by rw [hinv, hinv]
  let : CommGroup G := { (inferInstance : Group G) with mul_comm := hcomm }
  let : Module (ZMod 2) (Additive G) :=
    AddCommGroup.zmodModule (n := 2) (by
      intro x
      have h2 : (2 : ℕ) • x = x + x := two_nsmul x
      rw [h2]
      exact hG (Additive.toMul x))
  have : Finite (Additive G) := inferInstanceAs (Finite G)
  have : Fintype (Additive G) := Fintype.ofFinite _
  refine ⟨Module.finrank (ZMod 2) (Additive G), ?_⟩
  rw [Nat.card_congr (Additive.toMul : Additive G ≃ G).symm, Nat.card_eq_fintype_card,
    Module.card_eq_pow_finrank (K := ZMod 2) (V := Additive G)]
  simp
/-- A finite group of exponent `2` and order at most `2 ^ m` embeds into `F₂ ^ m`. -/
theorem exists_injective_hom_of_exponent_two {G : Type*} [Group G] [Finite G]
    (hG : ∀ g : G, g * g = 1) {m : ℕ} (hcard : Nat.card G ≤ 2 ^ m) :
    ∃ f : G →* Multiplicative (Fin m → ZMod 2), Function.Injective f := by
  classical
  have hcomm : ∀ a b : G, a * b = b * a := by
    intro a b
    have hinv : ∀ g : G, g⁻¹ = g := fun g => by rw [inv_eq_iff_mul_eq_one]; exact hG g
    calc a * b = (a * b)⁻¹ := by rw [hinv]
      _ = b⁻¹ * a⁻¹ := mul_inv_rev a b
      _ = b * a := by rw [hinv, hinv]
  let : CommGroup G := { (inferInstance : Group G) with mul_comm := hcomm }
  let : Module (ZMod 2) (Additive G) :=
    AddCommGroup.zmodModule (n := 2) (by
      intro x
      have h2 : (2 : ℕ) • x = x + x := two_nsmul x
      rw [h2]
      exact hG (Additive.toMul x))
  have : Finite (Additive G) := inferInstanceAs (Finite G)
  have : Module.Finite (ZMod 2) (Additive G) := Module.Finite.of_finite
  have : Fintype (Additive G) := Fintype.ofFinite _
  set D := Module.finrank (ZMod 2) (Additive G) with hD
  have hcardD : Nat.card G = 2 ^ D := by
    rw [Nat.card_congr (Additive.toMul : Additive G ≃ G).symm, Nat.card_eq_fintype_card,
      Module.card_eq_pow_finrank (K := ZMod 2) (V := Additive G)]
    simp [hD]
  have hDm : D ≤ m := by
    have h : (2 : ℕ) ^ D ≤ 2 ^ m := by rw [← hcardD]; exact hcard
    exact (Nat.pow_le_pow_iff_right (by norm_num)).mp h
  let B := Module.finBasis (ZMod 2) (Additive G)
  let L : Additive G ≃ₗ[ZMod 2] (Fin D → ZMod 2) := B.equivFun
  let pad : (Fin D → ZMod 2) → (Fin m → ZMod 2) :=
    fun v j => if h : (j : ℕ) < D then v ⟨j, h⟩ else 0
  have hpadadd : ∀ v w, pad (v + w) = pad v + pad w := by
    intro v w
    funext j
    by_cases h : (j : ℕ) < D <;> simp [pad, h]
  have hpadinj : Function.Injective pad := by
    intro v w h
    funext i
    have hi : (i : ℕ) < m := lt_of_lt_of_le i.2 hDm
    have h2 := congrFun h ⟨i, hi⟩
    simpa [pad, i.2] using h2
  refine ⟨MonoidHom.mk' (fun g => Multiplicative.ofAdd (pad (L (Additive.ofMul g)))) ?_, ?_⟩
  · intro a b
    show Multiplicative.ofAdd (pad (L (Additive.ofMul (a * b)))) =
      Multiplicative.ofAdd (pad (L (Additive.ofMul a))) *
        Multiplicative.ofAdd (pad (L (Additive.ofMul b)))
    have hadd : L (Additive.ofMul (a * b)) = L (Additive.ofMul a) + L (Additive.ofMul b) := by
      rw [show Additive.ofMul (a * b) = Additive.ofMul a + Additive.ofMul b from rfl]
      exact map_add L _ _
    rw [hadd, hpadadd]
    rfl
  · intro a b hab
    have h1 : pad (L (Additive.ofMul a)) = pad (L (Additive.ofMul b)) := hab
    exact Additive.ofMul.injective (L.injective (hpadinj h1))
private lemma two_mul_le_two_pow (d : ℕ) : 2 * d ≤ 2 ^ d := by
  induction d with
  | zero => simp
  | succ k ih =>
      rcases Nat.eq_zero_or_pos k with rfl | hk
      · norm_num
      · have h2 : (2 : ℕ) ^ 1 ≤ 2 ^ k := Nat.pow_le_pow_right (by norm_num) hk
        have h3 : (2 : ℕ) ^ (k + 1) = 2 * 2 ^ k := by ring
        simp at h2
        omega
/-- **The classical order bound.**  An elementary abelian `2`-subgroup of `S n` has order at
most `2 ^ ⌊n/2⌋`. -/
theorem card_le_of_exponent_two_perm (n : ℕ) (A : Subgroup (Perm (Fin n)))
    (hA : ∀ g ∈ A, g * g = 1) : Nat.card A ≤ 2 ^ (n / 2) := by
  classical
  have hAcomm : ∀ g h : A, (g : Perm (Fin n)) * (h : Perm (Fin n))
      = (h : Perm (Fin n)) * (g : Perm (Fin n)) := by
    intro g h
    have hinv : ∀ k : A, ((k : Perm (Fin n)))⁻¹ = (k : Perm (Fin n)) := by
      intro k
      rw [inv_eq_iff_mul_eq_one]
      exact hA k k.2
    have hgh : ((g * h : A) : Perm (Fin n)) = (g : Perm (Fin n)) * (h : Perm (Fin n)) := rfl
    calc (g : Perm (Fin n)) * (h : Perm (Fin n))
        = ((g : Perm (Fin n)) * (h : Perm (Fin n)))⁻¹ := by rw [← hgh, hinv (g * h), hgh]
      _ = ((h : Perm (Fin n)))⁻¹ * ((g : Perm (Fin n)))⁻¹ := mul_inv_rev _ _
      _ = (h : Perm (Fin n)) * (g : Perm (Fin n)) := by rw [hinv, hinv]
  set orb : Fin n → Finset (Fin n) :=
    fun x => Finset.univ.filter (fun y => ∃ g : A, (g : Perm (Fin n)) x = y) with horb
  have hmem : ∀ x y, y ∈ orb x ↔ ∃ g : A, (g : Perm (Fin n)) x = y := by
    intro x y; simp [horb]
  have hself : ∀ x, x ∈ orb x := by
    intro x; rw [hmem]; exact ⟨1, rfl⟩
  have htrans : ∀ x y, y ∈ orb x → orb y = orb x := by
    intro x y hy
    obtain ⟨g, hg⟩ := (hmem x y).mp hy
    ext z
    rw [hmem, hmem]
    constructor
    · rintro ⟨h, rfl⟩
      refine ⟨h * g, ?_⟩
      show (h : Perm (Fin n)) ((g : Perm (Fin n)) x) = _
      rw [hg]
    · rintro ⟨h, rfl⟩
      refine ⟨h * g⁻¹, ?_⟩
      show (h : Perm (Fin n)) (((g : Perm (Fin n)))⁻¹ y) = _
      rw [← hg]
      simp
  set c : Fin n → Fin n := fun x => (orb x).min' ⟨x, hself x⟩ with hcdef
  have hcmem : ∀ x, c x ∈ orb x := fun x => (orb x).min'_mem _
  have hceq : ∀ x y, y ∈ orb x → c y = c x := by
    intro x y hy
    simp only [hcdef]
    congr 1
    exact htrans x y hy
  have hcc : ∀ x, c (c x) = c x := fun x => hceq x (c x) (hcmem x)
  set T : Finset (Fin n) := Finset.univ.filter (fun x => c x = x) with hT
  have hcT : ∀ x, c x ∈ T := by intro x; simp [hT, hcc x]
  have hstabfix : ∀ (k : A) (x y : Fin n), y ∈ orb x → (k : Perm (Fin n)) x = x →
      (k : Perm (Fin n)) y = y := by
    intro k x y hy hkx
    obtain ⟨a, ha⟩ := (hmem x y).mp hy
    have hc := hAcomm k a
    have happ : (k : Perm (Fin n)) ((a : Perm (Fin n)) x)
        = (a : Perm (Fin n)) ((k : Perm (Fin n)) x) := by
      have h1 : ((k : Perm (Fin n)) * (a : Perm (Fin n))) x
          = ((a : Perm (Fin n)) * (k : Perm (Fin n))) x := by rw [hc]
      simpa [Perm.mul_apply] using h1
    rw [← ha, happ, hkx, ha]
  have hΦinj : Function.Injective
      (fun (g : A) (x : {x : Fin n // x ∈ T}) =>
        (⟨(g : Perm (Fin n)) x.1, (hmem _ _).mpr ⟨g, rfl⟩⟩ : {y : Fin n // y ∈ orb x.1})) := by
    intro g h hgh
    have hpt : ∀ x : Fin n, x ∈ T → (g : Perm (Fin n)) x = (h : Perm (Fin n)) x := by
      intro x hx
      have := congrFun hgh ⟨x, hx⟩
      exact congrArg Subtype.val this
    have hall : ∀ y : Fin n, (g : Perm (Fin n)) y = (h : Perm (Fin n)) y := by
      intro y
      set k : A := g⁻¹ * h with hk
      have hkb : (k : Perm (Fin n)) (c y) = c y := by
        show ((g : Perm (Fin n)))⁻¹ ((h : Perm (Fin n)) (c y)) = c y
        rw [← hpt (c y) (hcT y)]
        simp
      have hyorb : y ∈ orb (c y) := by
        have h5 := htrans y (c y) (hcmem y)
        rw [h5]
        exact hself y
      have hky := hstabfix k (c y) y hyorb hkb
      have h6 : ((g : Perm (Fin n)))⁻¹ ((h : Perm (Fin n)) y) = y := hky
      have h2 := congrArg (fun z => (g : Perm (Fin n)) z) h6
      simpa using h2.symm
    exact Subtype.ext (Equiv.ext hall)
  have hcard1 : Nat.card A ≤ ∏ x : {x : Fin n // x ∈ T}, (orb x.1).card := by
    refine le_trans (Nat.card_le_card_of_injective _ hΦinj) ?_
    rw [Nat.card_pi]
    refine le_of_eq (Finset.prod_congr rfl ?_)
    intro x _
    simp [Nat.card_eq_fintype_card]
  obtain ⟨D, hD⟩ : ∃ D : ℕ, Nat.card A = 2 ^ D :=
    exists_card_eq_two_pow_of_exponent_two (G := A) (fun g => Subtype.ext (hA g g.2))
  have hdvd : ∀ x : Fin n, (orb x).card ∣ Nat.card A := by
    intro x
    have e2 : {y : Fin n // y ∈ orb x} ≃ MulAction.orbit A x :=
      Equiv.subtypeEquivRight (fun y => by
        rw [hmem]
        constructor
        · rintro ⟨g, hg⟩; exact ⟨g, hg⟩
        · rintro ⟨g, hg⟩; exact ⟨g, hg⟩)
    have e1 : Nat.card {y : Fin n // y ∈ orb x} = (orb x).card := by
      simp [Nat.card_eq_fintype_card]
    rw [← e1, Nat.card_congr e2, Nat.card_congr (MulAction.orbitEquivQuotientStabilizer A x)]
    exact Subgroup.card_quotient_dvd_card _
  have hpow : ∀ x : Fin n, ∃ d : ℕ, (orb x).card = 2 ^ d := by
    intro x
    have h1 : (orb x).card ∣ 2 ^ D := by rw [← hD]; exact hdvd x
    obtain ⟨d, -, hd⟩ := (Nat.dvd_prime_pow Nat.prime_two).mp h1
    exact ⟨d, hd⟩
  choose d hd using hpow
  have hdisj : ∀ x ∈ T, ∀ y ∈ T, x ≠ y → Disjoint (orb x) (orb y) := by
    intro x hx y hy hxy
    rw [Finset.disjoint_left]
    intro z hzx hzy
    have h1 : orb z = orb x := htrans x z hzx
    have h2 : orb z = orb y := htrans y z hzy
    have h3 : orb x = orb y := by rw [← h1, h2]
    have h4 : c x = c y := by simp only [hcdef]; congr 1
    have hx' : c x = x := by simpa [hT] using hx
    have hy' : c y = y := by simpa [hT] using hy
    exact hxy (by rw [← hx', h4, hy'])
  have hdisj' : (T : Set (Fin n)).PairwiseDisjoint orb := by
    intro x hx y hy hxy
    exact hdisj x (Finset.mem_coe.mp hx) y (Finset.mem_coe.mp hy) hxy
  have hsum : ∑ x ∈ T, (orb x).card ≤ n := by
    calc ∑ x ∈ T, (orb x).card = (T.biUnion orb).card := (Finset.card_biUnion hdisj').symm
      _ ≤ Finset.univ.card := Finset.card_le_univ _
      _ = n := by simp
  have hsumd : 2 * (∑ x ∈ T, d x) ≤ n := by
    calc 2 * (∑ x ∈ T, d x) = ∑ x ∈ T, 2 * d x := by rw [Finset.mul_sum]
      _ ≤ ∑ x ∈ T, (orb x).card := by
          refine Finset.sum_le_sum ?_
          intro x _
          rw [hd x]
          exact two_mul_le_two_pow (d x)
      _ ≤ n := hsum
  calc Nat.card A ≤ ∏ x : {x : Fin n // x ∈ T}, (orb x.1).card := hcard1
    _ = ∏ x ∈ T, (orb x).card := Finset.prod_coe_sort T (fun x => (orb x).card)
    _ = ∏ x ∈ T, 2 ^ d x := Finset.prod_congr rfl (fun x _ => hd x)
    _ = 2 ^ (∑ x ∈ T, d x) := Finset.prod_pow_eq_pow_sum T d 2
    _ ≤ 2 ^ (n / 2) := Nat.pow_le_pow_right (by norm_num) (by omega)
/-- Each point can be labelled by a representative of its orbit. -/
theorem exists_orbit_labelling (n : ℕ) (A : Subgroup (Perm (Fin n))) :
    ∃ c : Fin n → Fin n,
      (∀ x, ∃ g : A, (g : Perm (Fin n)) (c x) = x) ∧
      (∀ (g : A) (x : Fin n), c ((g : Perm (Fin n)) x) = c x) := by
  classical
  set orb : Fin n → Finset (Fin n) :=
    fun x => Finset.univ.filter (fun y => ∃ g : A, (g : Perm (Fin n)) x = y) with horb
  have hmem : ∀ x y, y ∈ orb x ↔ ∃ g : A, (g : Perm (Fin n)) x = y := by
    intro x y; simp [horb]
  have hself : ∀ x, x ∈ orb x := by
    intro x; rw [hmem]; exact ⟨1, rfl⟩
  have htrans : ∀ x y, y ∈ orb x → orb y = orb x := by
    intro x y hy
    obtain ⟨g, hg⟩ := (hmem x y).mp hy
    ext z
    rw [hmem, hmem]
    constructor
    · rintro ⟨h, rfl⟩
      refine ⟨h * g, ?_⟩
      show (h : Perm (Fin n)) ((g : Perm (Fin n)) x) = _
      rw [hg]
    · rintro ⟨h, rfl⟩
      refine ⟨h * g⁻¹, ?_⟩
      show (h : Perm (Fin n)) (((g : Perm (Fin n)))⁻¹ y) = _
      rw [← hg]
      simp
  set c : Fin n → Fin n := fun x => (orb x).min' ⟨x, hself x⟩ with hc
  have hcmem : ∀ x, c x ∈ orb x := fun x => (orb x).min'_mem _
  refine ⟨c, ?_, ?_⟩
  · intro x
    obtain ⟨g, hg⟩ := (hmem x (c x)).mp (hcmem x)
    refine ⟨g⁻¹, ?_⟩
    show ((g : Perm (Fin n)))⁻¹ (c x) = x
    rw [← hg]
    simp
  · intro g x
    have hgx : (g : Perm (Fin n)) x ∈ orb x := (hmem _ _).mpr ⟨g, rfl⟩
    have heq := htrans x _ hgx
    simp only [hc]
    congr 1
/-- For every point `b` there is a homomorphism from an elementary abelian `A ≤ S n` to the
coordinate space whose kernel is exactly the stabiliser of `b`; it is obtained from the
embedding of `A / A_b` (a group of order `|orbit of b| ≤ n`) into `F₂ ^ (⌊log₂ n⌋ + 1)`. -/
theorem exists_hom_ker_stabilizer (n : ℕ) (A : Subgroup (Perm (Fin n)))
    (hA : ∀ g ∈ A, g * g = 1) (b : Fin n) :
    ∃ f : A →* Multiplicative (Coord n), ∀ g : A, (f g = 1 ↔ (g : Perm (Fin n)) b = b) := by
  classical
  have hAcomm : ∀ g h : A, g * h = h * g := by
    intro g h
    have hinv : ∀ k : A, k⁻¹ = k := by
      intro k
      rw [inv_eq_iff_mul_eq_one]
      exact Subtype.ext (hA k k.2)
    calc g * h = (g * h)⁻¹ := by rw [hinv]
      _ = h⁻¹ * g⁻¹ := mul_inv_rev _ _
      _ = h * g := by rw [hinv, hinv]
  set S := MulAction.stabilizer A b with hS
  have : S.Normal := by
    constructor
    intro x hx g
    have hgx : g * x * g⁻¹ = x := by
      rw [hAcomm g x, mul_assoc, mul_inv_cancel, mul_one]
    rw [hgx]
    exact hx
  have hQexp : ∀ q : A ⧸ S, q * q = 1 := by
    intro q
    induction q using QuotientGroup.induction_on with
    | H g =>
        have h1 : (g : A) * g = 1 := Subtype.ext (hA g g.2)
        show (QuotientGroup.mk (g * g) : A ⧸ S) = 1
        rw [h1]
        rfl
  have hQcard : Nat.card (A ⧸ S) ≤ 2 ^ (Nat.log 2 n + 1) := by
    have h1 : Nat.card (A ⧸ S) = Nat.card (MulAction.orbit A b) :=
      (Nat.card_congr (MulAction.orbitEquivQuotientStabilizer A b)).symm
    have h2 : Nat.card (MulAction.orbit A b) ≤ n := by
      have := Nat.card_le_card_of_injective (fun y : MulAction.orbit A b => (y : Fin n))
        Subtype.val_injective
      simpa using this
    have h3 : n < 2 ^ (Nat.log 2 n + 1) := Nat.lt_pow_succ_log_self (by norm_num) n
    omega
  obtain ⟨ψ, hψ⟩ := exists_injective_hom_of_exponent_two hQexp hQcard
  refine ⟨ψ.comp (QuotientGroup.mk' S), ?_⟩
  intro g
  constructor
  · intro h
    have h1 : ψ (QuotientGroup.mk' S g) = 1 := h
    have h2 : (QuotientGroup.mk' S) g = 1 := by
      refine hψ ?_
      rw [h1, map_one]
    rw [QuotientGroup.mk'_apply, QuotientGroup.eq_one_iff] at h2
    exact h2
  · intro h
    have h2 : (QuotientGroup.mk' S) g = 1 := by
      rw [QuotientGroup.mk'_apply, QuotientGroup.eq_one_iff]
      exact h
    show ψ ((QuotientGroup.mk' S) g) = 1
    rw [h2, map_one]
/-- **The structure theorem.**  Every elementary abelian `2`-subgroup of `S n` is contained in
a block translation group whose coordinates separate points inside blocks. -/
theorem exists_block_data (n : ℕ) (A : Subgroup (Perm (Fin n))) (hA : ∀ g ∈ A, g * g = 1) :
    ∃ (c : Fin n → Fin n) (o : Fin n → Coord n),
      (∀ x y : Fin n, c x = c y → o x = o y → x = y) ∧ A ≤ blockTransGroup n c o := by
  classical
  obtain ⟨c, hcex, hcinv⟩ := exists_orbit_labelling n A
  choose φ hφ using fun b => exists_hom_ker_stabilizer n A hA b
  choose gx hgx using hcex
  set o : Fin n → Coord n := fun x => Multiplicative.toAdd (φ (c x) (gx x)) with ho
  have hwd : ∀ (b : Fin n) (k1 k2 : A), (k1 : Perm (Fin n)) b = (k2 : Perm (Fin n)) b →
      φ b k1 = φ b k2 := by
    intro b k1 k2 h
    have h1 : φ b (k2⁻¹ * k1) = 1 := by
      rw [hφ b]
      show ((k2 : Perm (Fin n)))⁻¹ ((k1 : Perm (Fin n)) b) = b
      rw [h]
      simp
    rw [map_mul, map_inv, inv_mul_eq_one] at h1
    exact h1.symm
  refine ⟨c, o, ?_, ?_⟩
  · intro x y hcxy hoxy
    have h1 : φ (c x) (gx x) = φ (c x) (gx y) := by
      have h0 : Multiplicative.toAdd (φ (c x) (gx x))
          = Multiplicative.toAdd (φ (c y) (gx y)) := hoxy
      rw [hcxy]
      exact Multiplicative.toAdd.injective (by rw [← hcxy] at h0 ⊢; exact h0)
    have h2 : φ (c x) ((gx y)⁻¹ * (gx x)) = 1 := by
      rw [map_mul, map_inv, h1, inv_mul_cancel]
    rw [hφ (c x)] at h2
    have h3 : ((gx y : Perm (Fin n)))⁻¹ ((gx x : Perm (Fin n)) (c x)) = c x := h2
    rw [hgx x] at h3
    have h4 : (gx y : Perm (Fin n)) (c x) = x := by
      have h5 := congrArg (fun z => (gx y : Perm (Fin n)) z) h3
      simpa using h5.symm
    rw [hcxy, hgx y] at h4
    exact h4.symm
  · intro g hg
    refine ⟨fun x => hcinv ⟨g, hg⟩ x, ?_⟩
    have key : ∀ x : Fin n, o (g x) - o x = Multiplicative.toAdd (φ (c x) ⟨g, hg⟩) := by
      intro x
      have hcgx : c (g x) = c x := hcinv ⟨g, hg⟩ x
      have h1 : (gx (g x) : Perm (Fin n)) (c (g x)) = g x := hgx (g x)
      have h2 : ((⟨g, hg⟩ * gx x : A) : Perm (Fin n)) (c (g x)) = g x := by
        show g ((gx x : Perm (Fin n)) (c (g x))) = g x
        rw [hcgx, hgx x]
      have h3 : φ (c (g x)) (gx (g x)) = φ (c (g x)) (⟨g, hg⟩ * gx x) :=
        hwd _ _ _ (by rw [h1, h2])
      have h4 : o (g x) = Multiplicative.toAdd (φ (c (g x)) (gx (g x))) := rfl
      rw [h4, h3, map_mul]
      simp only [toAdd_mul]
      rw [hcgx]
      have h5 : o x = Multiplicative.toAdd (φ (c x) (gx x)) := rfl
      rw [h5]
      abel
    intro x y hxy
    rw [key x, key y, hxy]
/-- The number of elementary abelian `2`-subgroups of `S n`. -/
noncomputable def numElemAbSubgroupsSymm (n : ℕ) : ℕ :=
  Nat.card {H : Subgroup (Perm (Fin n)) // ∀ g ∈ H, g * g = 1}
/-- A block translation group whose coordinates separate points inside blocks has at most
`2 ^ (⌊n/2⌋ + ⌊n/2⌋²/4)` subgroups. -/
theorem card_subgroups_le_blockTransGroup (n : ℕ) (c : Fin n → Fin n) (o : Fin n → Coord n)
    (hinj : ∀ x y : Fin n, c x = c y → o x = o y → x = y) :
    Nat.card {B : Subgroup (Perm (Fin n)) // B ≤ blockTransGroup n c o}
      ≤ 2 ^ (n / 2 + (n / 2) * (n / 2) / 4) := by
  classical
  set E := blockTransGroup n c o with hE
  have hexp : ∀ g ∈ E, g * g = 1 := blockTransGroup_exponent_two n c o hinj
  have hEexp : ∀ g : E, g * g = 1 := fun g => Subtype.ext (hexp g g.2)
  obtain ⟨D, hD⟩ := exists_card_eq_two_pow_of_exponent_two (G := E) hEexp
  have hDle : D ≤ n / 2 := by
    have h1 : (2 : ℕ) ^ D ≤ 2 ^ (n / 2) := by
      rw [← hD]
      exact card_le_of_exponent_two_perm n E hexp
    exact (Nat.pow_le_pow_iff_right (by norm_num)).mp h1
  have hcard : Nat.card (Subgroup E) ≤ 2 ^ (D + D * D / 4) :=
    card_subgroup_le_of_exponent_two hEexp hD
  have hinj2 : Function.Injective
      (fun B : {B : Subgroup (Perm (Fin n)) // B ≤ E} => Subgroup.comap E.subtype B.1) := by
    intro B1 B2 h
    have h' : Subgroup.comap E.subtype B1.1 = Subgroup.comap E.subtype B2.1 := h
    apply Subtype.ext
    apply le_antisymm
    · intro x hx
      have hxE : x ∈ E := B1.2 hx
      have hmem : (⟨x, hxE⟩ : E) ∈ Subgroup.comap E.subtype B1.1 := hx
      rw [h'] at hmem
      exact hmem
    · intro x hx
      have hxE : x ∈ E := B2.2 hx
      have hmem : (⟨x, hxE⟩ : E) ∈ Subgroup.comap E.subtype B2.1 := hx
      rw [← h'] at hmem
      exact hmem
  calc Nat.card {B : Subgroup (Perm (Fin n)) // B ≤ E}
      ≤ Nat.card (Subgroup E) := Nat.card_le_card_of_injective _ hinj2
    _ ≤ 2 ^ (D + D * D / 4) := hcard
    _ ≤ 2 ^ (n / 2 + (n / 2) * (n / 2) / 4) := by
        refine Nat.pow_le_pow_right (by norm_num) ?_
        have hmul : D * D / 4 ≤ (n / 2) * (n / 2) / 4 :=
          Nat.div_le_div_right (Nat.mul_le_mul hDle hDle)
        omega
/-- **The sharp upper bound.**  `S n` has at most `n ^ n * (2n) ^ n * 2 ^ (⌊n/2⌋ + ⌊n/2⌋²/4)`
elementary abelian `2`-subgroups; the last factor is `2 ^ (n²/16 + O(n))` and the first two
are `2 ^ O(n log n)`. -/
theorem numElemAbSubgroupsSymm_le (n : ℕ) (hn : 1 ≤ n) :
    numElemAbSubgroupsSymm n ≤
      (n ^ n * (2 * n) ^ n) * 2 ^ (n / 2 + (n / 2) * (n / 2) / 4) := by
  classical
  choose c o hinj hle using fun (H : {H : Subgroup (Perm (Fin n)) // ∀ g ∈ H, g * g = 1}) =>
    exists_block_data n H.1 H.2
  set Pair := {p : (Fin n → Fin n) × (Fin n → Coord n) //
      ∀ x y : Fin n, p.1 x = p.1 y → p.2 x = p.2 y → x = y} with hPair
  have : Fintype Pair := Fintype.ofFinite _
  set Tot := (p : Pair) × {B : Subgroup (Perm (Fin n)) // B ≤ blockTransGroup n p.1.1 p.1.2}
    with hTot
  have hFinj : Function.Injective
      (fun H : {H : Subgroup (Perm (Fin n)) // ∀ g ∈ H, g * g = 1} =>
        (⟨⟨(c H, o H), hinj H⟩, ⟨H.1, hle H⟩⟩ : Tot)) := by
    intro H1 H2 h
    have h' : ((⟨⟨(c H1, o H1), hinj H1⟩, ⟨H1.1, hle H1⟩⟩ : Tot))
        = ⟨⟨(c H2, o H2), hinj H2⟩, ⟨H2.1, hle H2⟩⟩ := h
    have h2 := congrArg (fun s : Tot => (s.2 : Subgroup (Perm (Fin n)))) h'
    exact Subtype.ext h2
  have hstep1 : numElemAbSubgroupsSymm n ≤ Nat.card Tot :=
    Nat.card_le_card_of_injective _ hFinj
  have hstep2 : Nat.card Tot = ∑ p : Pair,
      Nat.card {B : Subgroup (Perm (Fin n)) // B ≤ blockTransGroup n p.1.1 p.1.2} :=
    Nat.card_sigma
  have hstep3 : ∑ p : Pair,
      Nat.card {B : Subgroup (Perm (Fin n)) // B ≤ blockTransGroup n p.1.1 p.1.2}
      ≤ ∑ _p : Pair, 2 ^ (n / 2 + (n / 2) * (n / 2) / 4) := by
    refine Finset.sum_le_sum ?_
    intro p _
    exact card_subgroups_le_blockTransGroup n p.1.1 p.1.2 p.2
  have hcardPair : Nat.card Pair ≤ n ^ n * (2 * n) ^ n := by
    have h1 : Nat.card Pair ≤ Nat.card ((Fin n → Fin n) × (Fin n → Coord n)) :=
      Nat.card_le_card_of_injective (fun p => p.1) Subtype.val_injective
    have h2 : Nat.card ((Fin n → Fin n) × (Fin n → Coord n))
        = n ^ n * (2 ^ (Nat.log 2 n + 1)) ^ n := by
      rw [Nat.card_prod, Nat.card_fun, Nat.card_fun]
      simp [Nat.card_eq_fintype_card]
    have h3 : (2 : ℕ) ^ (Nat.log 2 n + 1) ≤ 2 * n := by
      have h4 := Nat.pow_log_le_self 2 (by omega : n ≠ 0)
      calc (2 : ℕ) ^ (Nat.log 2 n + 1) = 2 * 2 ^ (Nat.log 2 n) := by ring
        _ ≤ 2 * n := by omega
    calc Nat.card Pair ≤ n ^ n * (2 ^ (Nat.log 2 n + 1)) ^ n := by rw [← h2]; exact h1
      _ ≤ n ^ n * (2 * n) ^ n := Nat.mul_le_mul_left _ (Nat.pow_le_pow_left h3 n)
  calc numElemAbSubgroupsSymm n ≤ Nat.card Tot := hstep1
    _ = ∑ p : Pair, Nat.card {B : Subgroup (Perm (Fin n)) //
          B ≤ blockTransGroup n p.1.1 p.1.2} := hstep2
    _ ≤ ∑ _p : Pair, 2 ^ (n / 2 + (n / 2) * (n / 2) / 4) := hstep3
    _ = Nat.card Pair * 2 ^ (n / 2 + (n / 2) * (n / 2) / 4) := by
        simp [Finset.sum_const, Nat.card_eq_fintype_card, mul_comm]
    _ ≤ (n ^ n * (2 * n) ^ n) * 2 ^ (n / 2 + (n / 2) * (n / 2) / 4) :=
        Nat.mul_le_mul_right _ hcardPair
end SubgroupCount
/-!
# `log₂` of the number of elementary abelian `2`-subgroups of `S n` is `(1/16 + o(1)) n²`
Combining the lower-bound construction of section 5 (which produces `2 ^ (n²/16 - n)`
elementary abelian `2`-subgroups of `S n`) with the upper bound
`SubgroupCount.numElemAbSubgroupsSymm_le` we obtain the *sharp* asymptotics
`log₂ #{elementary abelian 2-subgroups of S n} / n² → 1/16`.
This is the analogue, for the class of elementary abelian `2`-subgroups, of the constant in
Pyber's theorem, proved here unconditionally and with no appeal to the classification of
finite simple groups.
-/
set_option maxRecDepth 8000
set_option maxHeartbeats 1000000
namespace SubgroupCount
open Equiv Filter
/-! ## The lower bound -/
/-- The subgroups produced by the graph construction are elementary abelian, so they can be
counted inside the class of elementary abelian `2`-subgroups. -/
theorem pow_le_numElemAbSubgroupsSymm (n : ℕ) :
    2 ^ ((n / 4) * (n / 2 - n / 4)) ≤ numElemAbSubgroupsSymm n := by
  classical
  set a := n / 4 with ha
  set b := n / 2 - n / 4 with hb
  have hab : 2 * (a + b) ≤ n := by omega
  have hcard : Nat.card (Fin b → Fin a → ZMod 2) = 2 ^ (a * b) := by simp [pow_mul]
  rw [← hcard, numElemAbSubgroupsSymm]
  refine Nat.card_le_card_of_injective
    (fun A => ⟨permGraphSubgroup n a b hab A, fun g hg =>
      sq_eq_one_of_mem_permGraphSubgroup n a b hab A hg⟩) ?_
  intro A B hAB
  exact permGraphSubgroup_injective n a b hab (Subtype.ext_iff.mp hAB)
theorem numElemAbSubgroupsSymm_pos (n : ℕ) : 0 < numElemAbSubgroupsSymm n :=
  lt_of_lt_of_le (Nat.two_pow_pos _) (pow_le_numElemAbSubgroupsSymm n)
/-- Lower bound in logarithmic form. -/
theorem logb_numElemAbSubgroupsSymm_ge (n : ℕ) :
    (n : ℝ) ^ 2 / 16 - n ≤ Real.logb 2 (numElemAbSubgroupsSymm n) := by
  have hpos : (0 : ℝ) < numElemAbSubgroupsSymm n := by
    exact_mod_cast numElemAbSubgroupsSymm_pos n
  have h : (2 : ℝ) ^ ((n : ℝ) ^ 2 / 16 - n) ≤ numElemAbSubgroupsSymm n :=
    two_pow_le_pow n _ (pow_le_numElemAbSubgroupsSymm n)
  exact (Real.le_logb_iff_rpow_le (by norm_num) hpos).mpr h
/-! ## The upper bound -/
private lemma nat_block_exponent_le (n : ℕ) :
    16 * (n / 2 + (n / 2) * (n / 2) / 4) ≤ 8 * n + n * n := by
  have h1 : 2 * (n / 2) ≤ n := by omega
  have h3 : 4 * ((n / 2) * (n / 2)) ≤ n * n := by
    calc 4 * ((n / 2) * (n / 2)) = (2 * (n / 2)) * (2 * (n / 2)) := by ring
      _ ≤ n * n := Nat.mul_le_mul h1 h1
  generalize hX : (n / 2) * (n / 2) = X at h3 ⊢
  generalize hW : n * n = W at h3 ⊢
  omega
/-- Upper bound in logarithmic form: `log₂ #{elem. abelian 2-subgroups} ≤ n²/16 + 2n log₂ n + 2n`. -/
theorem logb_numElemAbSubgroupsSymm_le (n : ℕ) (hn : 2 ≤ n) :
    Real.logb 2 (numElemAbSubgroupsSymm n) ≤ (n : ℝ) ^ 2 / 16 + 2 * n * Real.logb 2 n + 2 * n := by
  have hn1 : 1 ≤ n := by omega
  have hnR : (2 : ℝ) ≤ (n : ℝ) := by exact_mod_cast hn
  have hnpos : (0 : ℝ) < (n : ℝ) := by linarith
  set E : ℕ := n / 2 + (n / 2) * (n / 2) / 4 with hE
  have hbound : (numElemAbSubgroupsSymm n : ℝ) ≤ ((n : ℝ) ^ n * (2 * n) ^ n) * 2 ^ E := by
    have h := numElemAbSubgroupsSymm_le n hn1
    have : ((numElemAbSubgroupsSymm n : ℕ) : ℝ) ≤ (((n ^ n * (2 * n) ^ n) * 2 ^ E : ℕ) : ℝ) := by
      exact_mod_cast h
    simpa [Nat.cast_mul, Nat.cast_pow] using this
  have hpos : (0 : ℝ) < numElemAbSubgroupsSymm n := by
    exact_mod_cast numElemAbSubgroupsSymm_pos n
  have hlog : Real.logb 2 (numElemAbSubgroupsSymm n)
      ≤ Real.logb 2 (((n : ℝ) ^ n * (2 * n) ^ n) * 2 ^ E) := by
    unfold Real.logb
    gcongr
  have hval : Real.logb 2 (((n : ℝ) ^ n * (2 * n) ^ n) * 2 ^ E)
      = n * Real.logb 2 n + n * (1 + Real.logb 2 n) + E := by
    have h2n : (0 : ℝ) < 2 * (n : ℝ) := by linarith
    rw [Real.logb_mul (by positivity) (by positivity), Real.logb_mul (by positivity)
      (by positivity), Real.logb_pow, Real.logb_pow, Real.logb_pow, Real.logb_mul (by norm_num)
      (ne_of_gt hnpos)]
    simp [Real.logb_self_eq_one]
  have hEle : (E : ℝ) ≤ (n : ℝ) / 2 + (n : ℝ) ^ 2 / 16 := by
    have h : 16 * E ≤ 8 * n + n * n := nat_block_exponent_le n
    have hR : (16 : ℝ) * (E : ℝ) ≤ 8 * (n : ℝ) + (n : ℝ) * (n : ℝ) := by exact_mod_cast h
    nlinarith
  rw [hval] at hlog
  have hlogn : (0 : ℝ) ≤ Real.logb 2 n := Real.logb_nonneg (by norm_num) (by linarith)
  linarith
/-! ## The resulting sharp asymptotics -/
private lemma tendsto_logb_div_atTop : Tendsto (fun n : ℕ => Real.logb 2 (n : ℝ) / (n : ℝ))
    atTop (nhds 0) := by
  have h : Tendsto (fun u : ℝ => Real.log u / u) atTop (nhds 0) :=
    Real.isLittleO_log_id_atTop.tendsto_div_nhds_zero
  have h2 := h.const_mul (1 / Real.log 2)
  simp only [mul_zero] at h2
  have h3 : Tendsto (fun u : ℝ => Real.logb 2 u / u) atTop (nhds 0) := by
    refine h2.congr ?_
    intro u
    simp [Real.logb]
    ring
  exact h3.comp tendsto_natCast_atTop_atTop
private lemma tendsto_one_div_nat : Tendsto (fun n : ℕ => 1 / (n : ℝ)) atTop (nhds 0) := by
  simpa [one_div, Function.comp_def] using
    tendsto_inv_atTop_zero.comp tendsto_natCast_atTop_atTop
/-- **Sharp asymptotics for the elementary abelian `2`-subgroups of `S n`.**
`log₂ #{elementary abelian 2-subgroups of S n} / n² → 1/16`; equivalently, the number of
elementary abelian `2`-subgroups of `S n` is `2 ^ ((1/16 + o(1)) n²)`.  This is
unconditional and free of the classification of finite simple groups. -/
theorem tendsto_logb_numElemAbSubgroupsSymm :
    Tendsto (fun n : ℕ => Real.logb 2 (numElemAbSubgroupsSymm n) / (n : ℝ) ^ 2)
      atTop (nhds (1 / 16)) := by
  have hlow : Tendsto (fun n : ℕ => 1 / 16 - 1 / (n : ℝ)) atTop (nhds (1 / 16)) := by
    have := tendsto_one_div_nat
    simpa using (tendsto_const_nhds (x := (1 / 16 : ℝ)) (f := atTop (α := ℕ))).sub this
  have hhigh : Tendsto
      (fun n : ℕ => 1 / 16 + 2 * (Real.logb 2 (n : ℝ) / (n : ℝ)) + 2 * (1 / (n : ℝ)))
      atTop (nhds (1 / 16)) := by
    have h1 := (tendsto_logb_div_atTop.const_mul (2 : ℝ))
    have h2 := (tendsto_one_div_nat.const_mul (2 : ℝ))
    have h3 := ((tendsto_const_nhds (x := (1 / 16 : ℝ)) (f := atTop (α := ℕ))).add h1).add h2
    simpa using h3
  refine tendsto_of_tendsto_of_tendsto_of_le_of_le' hlow hhigh ?_ ?_
  · filter_upwards [eventually_ge_atTop 2] with n hn
    have hnR : (2 : ℝ) ≤ (n : ℝ) := by exact_mod_cast hn
    have hnpos : (0 : ℝ) < (n : ℝ) := by linarith
    have h := logb_numElemAbSubgroupsSymm_ge n
    have hsq : (0 : ℝ) < (n : ℝ) ^ 2 := by positivity
    rw [le_div_iff₀ hsq]
    have hexp : (1 / 16 - 1 / (n : ℝ)) * (n : ℝ) ^ 2 = (n : ℝ) ^ 2 / 16 - n := by
      field_simp
    rw [hexp]
    exact h
  · filter_upwards [eventually_ge_atTop 2] with n hn
    have hnR : (2 : ℝ) ≤ (n : ℝ) := by exact_mod_cast hn
    have hnpos : (0 : ℝ) < (n : ℝ) := by linarith
    have hsq : (0 : ℝ) < (n : ℝ) ^ 2 := by positivity
    have h := logb_numElemAbSubgroupsSymm_le n hn
    rw [div_le_iff₀ hsq]
    have hexp : (n : ℝ) ^ 2 / 16 + 2 * n * Real.logb 2 n + 2 * n
        = (1 / 16 + 2 * (Real.logb 2 (n : ℝ) / (n : ℝ)) + 2 * (1 / (n : ℝ))) * (n : ℝ) ^ 2 := by
      field_simp
    rw [← hexp]
    exact h
end SubgroupCount
/-!
# Pyber's theorem: what follows from its (CFSG-dependent) upper half
The results of section 6 are unconditional, but they pin down
`log₂ s(n)` (where `s(n)` is the number of subgroups of `S n`) only up to a factor
`⌈log₂ n⌉²`.  The sharp statement
  `s(n) = 2 ^ ((1/16 + o(1)) n²)`   (Pyber)
has an upper half whose only known proof uses the classification of finite simple groups.
That half is *not* proved in this project.  Instead, this file isolates it as an explicit
hypothesis — a `Prop`-valued definition that is passed as a theorem argument, never as an
axiom — and derives from it, completely and rigorously, the two statements that were left
open:
* `tendsto_logb_numSubgroupsSymm_of_pyber` :  assuming the Pyber upper bound,
  `log₂ s(n) / n² → 1/16`, i.e. `s(n) = 2 ^ ((1/16 + o(1)) n²)`;
* `tendsto_ratio_twoSubgroups_of_bound` :  assuming that the non-`2`-subgroups of `S n`
  number at most `2 ^ (n²/16 - 2n)`, almost all subgroups of `S n` are `2`-groups, i.e.
  `#{2-subgroups of S n} / s(n) → 1`.
The *lower* halves used in both derivations are the unconditional, CFSG-free results proved
elsewhere in this project.  In particular `two_pow_le_numTwoSubgroupsSymm` below shows,
unconditionally, that `S n` has at least `2 ^ (n²/16 - n)` subgroups which are `2`-groups.
-/
set_option maxHeartbeats 1000000
namespace SubgroupCount
open Equiv Filter
/-! ## Auxiliary limits -/
private lemma logb2_mono' {x y : ℝ} (hx : 0 < x) (h : x ≤ y) : Real.logb 2 x ≤ Real.logb 2 y := by
  unfold Real.logb
  gcongr
private lemma tendsto_one_div_nat' : Tendsto (fun n : ℕ => 1 / (n : ℝ)) atTop (nhds 0) := by
  simpa [one_div, Function.comp_def] using
    tendsto_inv_atTop_zero.comp tendsto_natCast_atTop_atTop
/-! ## The sharp asymptotics, conditional on Pyber's upper bound -/
/-- **The upper half of Pyber's theorem, as a hypothesis.**  For every `ε > 0`, eventually
`s(n) ≤ 2 ^ ((1/16 + ε) n²)`.  The only known proof of this statement uses the
classification of finite simple groups; it is *not* proved in this project. -/
def PyberUpperBound : Prop :=
  ∀ ε : ℝ, 0 < ε → ∀ᶠ n : ℕ in atTop,
    (numSubgroupsSymm n : ℝ) ≤ (2 : ℝ) ^ ((1 / 16 + ε) * (n : ℝ) ^ 2)
/-- **Pyber's asymptotic formula, conditionally.**  Granting the CFSG-dependent upper bound
`PyberUpperBound`, the unconditional lower bound of this project upgrades it to the sharp
asymptotics `log₂ s(n) / n² → 1/16`, i.e. `s(n) = 2 ^ ((1/16 + o(1)) n²)`. -/
theorem tendsto_logb_numSubgroupsSymm_of_pyber (h : PyberUpperBound) :
    Tendsto (fun n : ℕ => Real.logb 2 (numSubgroupsSymm n) / (n : ℝ) ^ 2) atTop
      (nhds (1 / 16)) := by
  refine tendsto_order.2 ⟨?_, ?_⟩
  · intro a ha
    have hlow : Tendsto (fun n : ℕ => 1 / 16 - 1 / (n : ℝ)) atTop (nhds (1 / 16)) := by
      simpa using (tendsto_const_nhds (x := (1 / 16 : ℝ)) (f := atTop (α := ℕ))).sub
        tendsto_one_div_nat'
    filter_upwards [hlow.eventually (eventually_gt_nhds ha), eventually_ge_atTop 1] with n hna hn1
    have hnR : (1 : ℝ) ≤ (n : ℝ) := by exact_mod_cast hn1
    have hnpos : (0 : ℝ) < (n : ℝ) := by linarith
    have hsq : (0 : ℝ) < (n : ℝ) ^ 2 := by positivity
    have hb : (2 : ℝ) ^ ((n : ℝ) ^ 2 / 16 - n) ≤ numSubgroupsSymm n :=
      two_pow_le_card_subgroups_symm n
    have hpos : (0 : ℝ) < numSubgroupsSymm n := by exact_mod_cast numSubgroupsSymm_pos n
    have hlogb : (n : ℝ) ^ 2 / 16 - n ≤ Real.logb 2 (numSubgroupsSymm n) := by
      have := logb2_mono' (Real.rpow_pos_of_pos (by norm_num) _) hb
      rwa [Real.logb_rpow (b := 2) (by norm_num) (by norm_num)] at this
    have hstep : (1 / 16 - 1 / (n : ℝ)) * (n : ℝ) ^ 2 ≤ Real.logb 2 (numSubgroupsSymm n) := by
      have hexp : (1 / 16 - 1 / (n : ℝ)) * (n : ℝ) ^ 2 = (n : ℝ) ^ 2 / 16 - n := by
        field_simp
      rw [hexp]; exact hlogb
    calc a < 1 / 16 - 1 / (n : ℝ) := hna
      _ ≤ Real.logb 2 (numSubgroupsSymm n) / (n : ℝ) ^ 2 := by rw [le_div_iff₀ hsq]; exact hstep
  · intro b hb
    have hε : (0 : ℝ) < (b - 1 / 16) / 2 := by linarith
    filter_upwards [h _ hε, eventually_ge_atTop 1] with n hbound hn1
    have hnR : (1 : ℝ) ≤ (n : ℝ) := by exact_mod_cast hn1
    have hsq : (0 : ℝ) < (n : ℝ) ^ 2 := by positivity
    have hpos : (0 : ℝ) < numSubgroupsSymm n := by exact_mod_cast numSubgroupsSymm_pos n
    have hlogb : Real.logb 2 (numSubgroupsSymm n)
        ≤ (1 / 16 + (b - 1 / 16) / 2) * (n : ℝ) ^ 2 := by
      have := logb2_mono' hpos hbound
      rwa [Real.logb_rpow (b := 2) (by norm_num) (by norm_num)] at this
    rw [div_lt_iff₀ hsq]
    have : (1 / 16 + (b - 1 / 16) / 2) * (n : ℝ) ^ 2 < b * (n : ℝ) ^ 2 := by
      apply mul_lt_mul_of_pos_right _ hsq
      linarith
    linarith
/-! ## Almost all subgroups are `2`-groups, conditionally -/
/-- The number of subgroups of `S n` that are `2`-groups. -/
noncomputable def numTwoSubgroupsSymm (n : ℕ) : ℕ :=
  Nat.card {H : Subgroup (Perm (Fin n)) // IsPGroup 2 H}
/-- The number of subgroups of `S n` that are *not* `2`-groups. -/
noncomputable def numNonTwoSubgroupsSymm (n : ℕ) : ℕ :=
  Nat.card {H : Subgroup (Perm (Fin n)) // ¬ IsPGroup 2 H}
/-- The subgroups of `S n` split into the `2`-groups and the rest. -/
theorem numTwoSubgroupsSymm_add_numNonTwoSubgroupsSymm (n : ℕ) :
    numTwoSubgroupsSymm n + numNonTwoSubgroupsSymm n = numSubgroupsSymm n := by
  classical
  rw [numTwoSubgroupsSymm, numNonTwoSubgroupsSymm, numSubgroupsSymm, ← Nat.card_sum]
  exact Nat.card_eq_of_bijective _
    (Equiv.sumCompl (fun H : Subgroup (Perm (Fin n)) => IsPGroup 2 H)).bijective
/-- **Unconditional.**  At least `2 ^ (n²/16 - n)` subgroups of `S n` are `2`-groups:
the elementary abelian subgroups of order `2 ^ ⌊n/4⌋` constructed in this project already
are that numerous. -/
theorem two_pow_le_numTwoSubgroupsSymm (n : ℕ) :
    (2 : ℝ) ^ ((n : ℝ) ^ 2 / 16 - n) ≤ numTwoSubgroupsSymm n := by
  refine le_trans (two_pow_le_card_subgroups_symm_of_order n) ?_
  have hle : Nat.card {H : Subgroup (Perm (Fin n)) // Nat.card H = 2 ^ (n / 4)}
      ≤ numTwoSubgroupsSymm n := by
    refine Nat.card_le_card_of_injective
      (fun H => ⟨H.1, IsPGroup.of_card H.2⟩) ?_
    intro H K hHK
    have h' : (H : Subgroup (Perm (Fin n))) = (K : Subgroup (Perm (Fin n))) :=
      congrArg (fun x : {H : Subgroup (Perm (Fin n)) // IsPGroup 2 H} =>
        (x : Subgroup (Perm (Fin n)))) hHK
    exact Subtype.ext h'
  exact_mod_cast hle
/-- **The hypothesis needed for the ratio statement.**  Eventually, the subgroups of `S n`
that are not `2`-groups number at most `2 ^ (n²/16 - 2n)`.  A bound of this strength is
exactly what the CFSG-dependent half of Pyber's theorem provides; it is *not* proved here. -/
def NonTwoSubgroupsBound : Prop :=
  ∀ᶠ n : ℕ in atTop, (numNonTwoSubgroupsSymm n : ℝ) ≤ (2 : ℝ) ^ ((n : ℝ) ^ 2 / 16 - 2 * n)
/-- **Almost all subgroups of `S n` are `2`-groups, conditionally.**  Granting
`NonTwoSubgroupsBound`, the proportion of subgroups of `S n` that are `2`-groups tends to `1`.
The lower bound on the number of `2`-subgroups used here is unconditional. -/
theorem tendsto_ratio_twoSubgroups_of_bound (h : NonTwoSubgroupsBound) :
    Tendsto (fun n : ℕ => (numTwoSubgroupsSymm n : ℝ) / numSubgroupsSymm n) atTop (nhds 1) := by
  have hone : Tendsto (fun n : ℕ => 1 - 1 / (n : ℝ)) atTop (nhds 1) := by
    simpa using (tendsto_const_nhds (x := (1 : ℝ)) (f := atTop (α := ℕ))).sub tendsto_one_div_nat'
  refine tendsto_of_tendsto_of_tendsto_of_le_of_le' hone tendsto_const_nhds ?_ ?_
  · filter_upwards [h, eventually_ge_atTop 1] with n hbound hn1
    have hnR : (1 : ℝ) ≤ (n : ℝ) := by exact_mod_cast hn1
    have hnpos : (0 : ℝ) < (n : ℝ) := by linarith
    set T : ℝ := (numTwoSubgroupsSymm n : ℝ) with hT
    set N : ℝ := (numNonTwoSubgroupsSymm n : ℝ) with hN
    have hTlow : (2 : ℝ) ^ ((n : ℝ) ^ 2 / 16 - n) ≤ T := two_pow_le_numTwoSubgroupsSymm n
    have hbase : (0 : ℝ) < (2 : ℝ) ^ ((n : ℝ) ^ 2 / 16 - n) := Real.rpow_pos_of_pos (by norm_num) _
    have hTpos : 0 < T := lt_of_lt_of_le hbase hTlow
    have hNnonneg : 0 ≤ N := by positivity
    have hsplit : T + N = (numSubgroupsSymm n : ℝ) := by
      have := numTwoSubgroupsSymm_add_numNonTwoSubgroupsSymm n
      rw [hT, hN, ← Nat.cast_add, this]
    have hSpos : (0 : ℝ) < T + N := by linarith
    -- `N ≤ 2⁻ⁿ * T`
    have hsplit2 : (2 : ℝ) ^ ((n : ℝ) ^ 2 / 16 - 2 * n)
        = (2 : ℝ) ^ (-(n : ℝ)) * (2 : ℝ) ^ ((n : ℝ) ^ 2 / 16 - n) := by
      rw [← Real.rpow_add (by norm_num)]
      ring_nf
    have hfac : (0 : ℝ) < (2 : ℝ) ^ (-(n : ℝ)) := Real.rpow_pos_of_pos (by norm_num) _
    have hNle : N ≤ (2 : ℝ) ^ (-(n : ℝ)) * T := by
      calc N ≤ (2 : ℝ) ^ ((n : ℝ) ^ 2 / 16 - 2 * n) := hbound
        _ = (2 : ℝ) ^ (-(n : ℝ)) * (2 : ℝ) ^ ((n : ℝ) ^ 2 / 16 - n) := hsplit2
        _ ≤ (2 : ℝ) ^ (-(n : ℝ)) * T := mul_le_mul_of_nonneg_left hTlow hfac.le
    -- `2⁻ⁿ ≤ 1/n`
    have hpow : (2 : ℝ) ^ (-(n : ℝ)) ≤ 1 / (n : ℝ) := by
      have hnn : (n : ℝ) ≤ (2 : ℝ) ^ (n : ℝ) := by
        have h1 : (n : ℝ) ≤ ((2 ^ n : ℕ) : ℝ) := by exact_mod_cast Nat.lt_two_pow_self.le
        have h2 : ((2 ^ n : ℕ) : ℝ) = (2 : ℝ) ^ (n : ℝ) := by
          rw [Real.rpow_natCast]; push_cast; ring
        linarith [h2 ▸ h1]
      have hp : (0 : ℝ) < (2 : ℝ) ^ (n : ℝ) := Real.rpow_pos_of_pos (by norm_num) _
      rw [Real.rpow_neg (by norm_num), inv_eq_one_div, div_le_div_iff₀ hp hnpos]
      linarith
    have hNle2 : N ≤ (1 / (n : ℝ)) * (T + N) := by
      have h1 : N ≤ (1 / (n : ℝ)) * T :=
        le_trans hNle (mul_le_mul_of_nonneg_right hpow (le_of_lt hTpos))
      have h2 : (1 / (n : ℝ)) * T ≤ (1 / (n : ℝ)) * (T + N) := by
        apply mul_le_mul_of_nonneg_left (by linarith) (by positivity)
      linarith
    rw [← hsplit, le_div_iff₀ hSpos]
    nlinarith
  · filter_upwards [eventually_ge_atTop 1] with n _
    have hsplit : (numTwoSubgroupsSymm n : ℝ) + (numNonTwoSubgroupsSymm n : ℝ)
        = (numSubgroupsSymm n : ℝ) := by
      have := numTwoSubgroupsSymm_add_numNonTwoSubgroupsSymm n
      rw [← Nat.cast_add, this]
    have hpos : (0 : ℝ) < numSubgroupsSymm n := by exact_mod_cast numSubgroupsSymm_pos n
    rw [div_le_one hpos]
    have : (0 : ℝ) ≤ (numNonTwoSubgroupsSymm n : ℝ) := by positivity
    linarith
end SubgroupCount
/-!
# Summary of the results proved in this project
`s(n) := Nat.card (Subgroup (Equiv.Perm (Fin n)))` is the number of subgroups of `S n`.
* `SubgroupCount.two_pow_le_card_subgroups_symm` :  `2 ^ (n²/16 - n) ≤ s(n)`.
* `SubgroupCount.card_subgroups_symm_le` :  `s(n) ≤ 2 ^ (n ⌈log₂ n⌉)²`.
* `SubgroupCount.tendsto_logb_logb_card_subgroups_symm` :  `log₂ s(n) = n ^ (2 + o(1))`.
* `SubgroupCount.two_pow_le_card_subgroups_symm_of_order` and
  `SubgroupCount.tendsto_logb_logb_card_subgroups_symm_of_order` :  the same growth is already
  achieved by the subgroups of the single order `2 ^ ⌊n/4⌋`, all of which are elementary
  abelian `2`-groups.
Sharp constant, unconditionally, for the extremal class of subgroups:
* `SubgroupCount.numElemAbSubgroupsSymm_le` and
  `SubgroupCount.tendsto_logb_numElemAbSubgroupsSymm` :
  `log₂ #{elementary abelian 2-subgroups of S n} / n² → 1/16`, so the number of elementary
  abelian `2`-subgroups of `S n` is exactly `2 ^ ((1/16 + o(1)) n²)`.  No appeal to the
  classification of finite simple groups is made anywhere in this project.
Conditional on the (CFSG-dependent) upper half of Pyber's theorem, stated as an explicit
hypothesis and never as an axiom (`RequestProject/Pyber.lean`):
* `SubgroupCount.tendsto_logb_numSubgroupsSymm_of_pyber` :  `log₂ s(n) / n² → 1/16`;
* `SubgroupCount.tendsto_ratio_twoSubgroups_of_bound` :  almost all subgroups of `S n` are
  `2`-groups.
* `SubgroupCount.two_pow_le_numTwoSubgroupsSymm` (unconditional) :  at least
  `2 ^ (n²/16 - n)` subgroups of `S n` are `2`-groups.
-/
#print axioms SubgroupCount.two_pow_le_card_subgroups_symm
#print axioms SubgroupCount.card_subgroups_symm_le
#print axioms SubgroupCount.tendsto_logb_logb_card_subgroups_symm
#print axioms SubgroupCount.two_pow_le_card_subgroups_symm_of_order
#print axioms SubgroupCount.tendsto_logb_logb_card_subgroups_symm_of_order
#print axioms SubgroupCount.numElemAbSubgroupsSymm_le
#print axioms SubgroupCount.tendsto_logb_numElemAbSubgroupsSymm
#print axioms SubgroupCount.two_pow_le_numTwoSubgroupsSymm
#print axioms SubgroupCount.tendsto_logb_numSubgroupsSymm_of_pyber
#print axioms SubgroupCount.tendsto_ratio_twoSubgroups_of_bound
